
INSERT INTO `answers` (`answer`, `deck`)
VALUES 
('Throwing grapes at a man until he loses touch with reality.', 'US'),
('My Uber driver, Pavel.', 'US'),
('The Hamburglar.', 'US'),
('A stray pube.', 'US'),
('White privilege.', 'US'),
('Facebook.', 'US'),
('Pac-Man uncontrollably guzzling cum.', 'US'),
('Forced sterilization.', 'US'),
('An Oedipus complex.', 'US'),
('Scientology.', 'US'),
('My fat daughter.', 'US'),
('Active listening.', 'US'),
('Vigorous jazz hands.', 'US'),
('An M. Night Shyamalan plot twist.', 'US'),
('The rhythms of Africa.', 'US'),
('The homosexual agenda.', 'US'),
('Having big dreams but no realistic way to achieve them.', 'US'),
('A time travel paradox.', 'US'),
('Lactation.', 'US'),
('Dick fingers.', 'US'),
('Dying.', 'US'),
('My good bra.', 'US'),
('Me time.', 'US'),
('Smallpox blankets.', 'US'),
('J.D. Power and his associates.', 'US'),
('Seeing my father cry.', 'US'),
('Seppuku.', 'US'),
('Adderall.&reg;', 'US'),
('Hot people.', 'US'),
('Dead babies.', 'US'),
('Not reciprocating oral sex.', 'US'),
('50 mg of Zoloft daily.', 'US'),
('A bleached asshole.', 'US'),
('Flesh-eating bacteria.', 'US'),
('Itchy pussy.', 'US'),
('Foreskin.', 'US'),
('Worshipping that pussy.', 'US'),
('How far I can get my own penis up my butt.', 'US'),
('World peace.', 'US'),
('Expecting a burp and vomiting on the floor.', 'US'),
('Kamikaze pilots.', 'US'),
('Anal beads.', 'US'),
('Being rich.', 'US'),
('The Three-Fifths Compromise.', 'US'),
('Shapeshifters.', 'US'),
('Lockjaw.', 'US'),
('Getting so angry that you pop a boner.', 'US'),
('Child beauty pageants.', 'US'),
('Breaking out into song and dance.', 'US'),
('Pretending to care.', 'US'),
('Waiting till marriage.', 'US'),
('The wifi password.', 'US'),
('Being a woman.', 'US'),
('The past.', 'US'),
('Catapults.', 'US'),
('A lifetime of sadness.', 'US'),
('Going an entire day without masturbating.', 'US'),
('Dwayne &quot;The Rock&quot; Johnson.', 'US'),
('A saxophone solo.', 'US'),
('Being marginalized.', 'US'),
('The penny whistle solo from &quot;My Heart Will Go On.&quot;', 'US'),
('A fart so powerful that it wakes the giants from their thousand-year slumber.', 'US'),
('My genitals.', 'US'),
('Little boy penises.', 'US'),
('Punching a congressman in the face.', 'US'),
('Some god damn peace and quiet.', 'US'),
('BATMAN!', 'US'),
('Ruth Bader Ginsburg brutally gaveling your penis.', 'US'),
('Preteens.', 'US'),
('More elephant cock than I bargained for.', 'US'),
('Smegma.', 'US'),
('A micropenis.', 'US'),
('My ugly face and bad personality.', 'US'),
('A good sniff.', 'US'),
('Explaining how vaginas work.', 'US'),
('Genuine human connection.', 'US'),
('An old guy who&apos;s almost dead.', 'US'),
('My cheating son-of-a-bitch husband.', 'US'),
('Fox News.', 'US'),
('Being a motherfucking sorcerer.', 'US'),
('The Red Hot Chili Peppers.', 'US'),
('Holding down a child and farting all over him.', 'US'),
('The KKK.', 'US'),
('Land mines.', 'US'),
('Centaurs.', 'US'),
('Seven dead and three in critical condition.', 'US'),
('My relationship status.', 'US'),
('A mating display.', 'US'),
('Auschwitz.', 'US'),
('Used panties.', 'US'),
('Alcoholism.', 'US'),
('Sexual peeing.', 'US'),
('A windmill full of corpses.', 'US'),
('Darth Vader.', 'US'),
('Daniel Radcliffe&apos;s delicious asshole.', 'US'),
('A good, strong gorilla.', 'US'),
('Huffing spray paint.', 'US'),
('Half-assed foreplay.', 'US'),
('Nipple blades.', 'US'),
('Being able to talk to elephants.', 'US'),
('Making a pouty face.', 'US'),
('Drowning the kids in the bathtub.', 'US'),
('Emerging from the sea and rampaging through Tokyo.', 'US'),
('Hospice care.', 'US'),
('Magnets.', 'US'),
('Touching a pug right on his penis.', 'US'),
('Vladimir Putin.', 'US'),
('Spontaneous human combustion.', 'US'),
('Leprosy.', 'US'),
('Seething with quiet resentment.', 'US'),
('Explosions.', 'US'),
('Licking things to claim them as your own.', 'US'),
('Consensual sex.', 'US'),
('Getting married, having a few kids, buying some stuff, retiring to Florida, and dying.', 'US'),
('Nickelback.', 'US'),
('The Boy Scouts of America.', 'US'),
('Bananas.', 'US'),
('Masturbating.', 'US'),
('All the dues I&apos;ve fucked.', 'US'),
('Famine.', 'US'),
('Hillary Clinton&apos;s emails.', 'US'),
('Executing a hostage every hour.', 'US'),
('Running out of semen.', 'US'),
('Jews, gypsies, and homosexuals.', 'US'),
('The arrival of the pizza.', 'US'),
('Goblins.', 'US'),
('Laying an egg.', 'US'),
('A bowl of mayonnaise and human teeth.', 'US'),
('A micropig wearing a tiny raincoat and booties.', 'US'),
('A bitch slap.', 'US'),
('Giving 110%.', 'US'),
('Inserting a Mason jar into my anus.', 'US'),
('A man on the brink of orgasm.', 'US'),
('A much younger woman.', 'US'),
('10,000 Syrian refugees.', 'US'),
('A sad handjob.', 'US'),
('Police brutality.', 'US'),
('Throwing a virgin into a volcano.', 'US'),
('A sea of troubles.', 'US'),
('Multiple stab wounds.', 'US'),
('Filling my briefcase with business stuff.', 'US'),
('A tiny horse.', 'US'),
('The Kool-Aid Man.', 'US'),
('Grandma.', 'US'),
('A bag of magic beans.', 'US'),
('Doing the right thing.', 'US'),
('Emma Watson.', 'US'),
('Racism.', 'US'),
('Powerful thighs.', 'US'),
('Men.', 'US'),
('Farting and walking away.', 'US'),
('Pedophiles.', 'US'),
('German Chancellor Angela Merkel.', 'US'),
('Peeing a little bit.', 'US'),
('Viagra.&reg;', 'US'),
('Ronald Reagan.', 'US'),
('Bisexuality.', 'US'),
('The clitoris.', 'US'),
('Soft, kissy missionary sex.', 'US'),
('Sitting on my face and telling me I&apos;m garbage.', 'US'),
('A balanced breakfast.', 'US'),
('Puberty.', 'US'),
('Poor people.', 'US'),
('Harry Potter erotica.', 'US'),
('Penis breath.', 'US'),
('Agriculture.', 'US'),
('Committing suicide.', 'US'),
('The heart of a child.', 'US'),
('Aaron Burr.', 'US'),
('Republicans.', 'US'),
('Justin Bieber.', 'US'),
('Concealing a boner.', 'US'),
('Not vaccinating my children because I am stupid.', 'US'),
('Judge Judy.', 'US'),
('Sex with animals.', 'US'),
('Men discussing their feelings in an emotionally healthy way.', 'US'),
('Dead birds everywhere.', 'US'),
('All-you-can-eat shrimp for $8.99.', 'US'),
('My bright pink fuckhole.', 'US'),
('Having sex for the first time.', 'US'),
('An endless stream of diarrhea.', 'US'),
('Getting drugs off the street and into my body.', 'US'),
('German dungeon porn.', 'US'),
('Bingeing and purging.', 'US'),
('Kourtney, Kim, Khloe, Kendall, and Kylie.', 'US'),
('Mouth herpes.', 'US'),
('Seeing what happens when you lock people in a room with hungry seagulls.', 'US'),
('72 virgins.', 'US'),
('Not giving a shit about the Third World.', 'US'),
('Getting cummed on.', 'US'),
('Poor life choices.', 'US'),
('Firing a rifle into the air while balls deep in a squealing hog.', 'US'),
('Opposable thumbs.', 'US'),
('Geese.', 'US'),
('Being fat and stupid.', 'US'),
('Fancy Feast.&reg;', 'US'),
('Serfdom.', 'US'),
('Teaching a robot to love.', 'US'),
('A Super Soaker&trade; full of cat pee.', 'US'),
('NBA superstar LeBron James.', 'US'),
('Child abuse.', 'US'),
('Fucking my sister.', 'US'),
('Natural male enhancement.', 'US'),
('Science.', 'US'),
('The Bachelorette season finale.', 'US'),
('The gays.', 'US'),
('Becoming a blueberry.', 'US'),
('Oprah.', 'US'),
('Three dicks at the same time.', 'US'),
('The wonders of the Orient.', 'US'),
('Puppies!', 'US'),
('An unwanted pregnancy.', 'US'),
('Racially-biased SAT questions.', 'US'),
('The Holy Bible.', 'US'),
('Women of color.', 'US'),
('However much weed $20 can buy.', 'US'),
('Doing crimes.', 'US'),
('A whole thing of butter.', 'US'),
('Having anuses for eyes.', 'US'),
('Silence.', 'US'),
('Lumberjack fantasies.', 'US'),
('My balls on your face.', 'US'),
('Dead parents.', 'US'),
('Barack Obama.', 'US'),
('A snapping turtle biting the tip of your penis.', 'US'),
('A salad for men that&apos;s made of metal.', 'US'),
('African children.', 'US'),
('Fading away into nothingness.', 'US'),
('Illegal immigrants.', 'US'),
('Spaghetti? Again?', 'US'),
('The Amish.', 'US'),
('Wizard music.', 'US'),
('The miracle of childbirth.', 'US'),
('Eating a hard boiled egg out of my husband&apos;s asshole.', 'US'),
('Selling crack to children.', 'US'),
('Menstrual rage.', 'US'),
('Still being a virgin.', 'US'),
('Mike Pence.', 'US'),
('Shiny objects.', 'US'),
('Giving birth to the Antichrist.', 'US'),
('The entire Mormon Tabernacle Choir.', 'US'),
('The placenta.', 'US'),
('Count Chocula.', 'US'),
('Bees?', 'US'),
('Drinking alone.', 'US'),
('Telling a shitty story that goes nowhere.', 'US'),
('Sunshine and rainbows.', 'US'),
('A little boy who won&apos;t shut the fuck up about dinosaurs.', 'US'),
('Finger painting.', 'US'),
('Hobos.', 'US'),
('Natural selection.', 'US'),
('An erection that lasts longer than four hours.', 'US'),
('Bubble butt bottom boys.', 'US'),
('My soul.', 'US'),
('A middle-aged man on roller skates.', 'US'),
('Being a dick to children.', 'US'),
('Mutually assured destruction.', 'US'),
('Eating the last known bison.', 'US'),
('A mopey zoo lion.', 'US'),
('The cool, refreshing taste of Pepsi.&reg;', 'US'),
('Extremely tight pants.', 'US'),
('Queefing.', 'US'),
('A live studio audience.', 'US'),
('An oversized lollipop.', 'US'),
('Nicolas Cage.', 'US'),
('The Rapture.', 'US'),
('Daddy issues.', 'US'),
('Chunks of dead hitchhiker.', 'US'),
('Accepting the way things are.', 'US'),
('The Big Bang.', 'US'),
('Women&apos;s suffrage.', 'US'),
('Inappropriate yodeling.', 'US'),
('An older woman who knows her way around the penis.', 'US'),
('Raptor attacks.', 'US'),
('Sex with Patrick Stewart.', 'US'),
('The Patriarchy.', 'US'),
('Free samples.', 'US'),
('My ex-wife.', 'US'),
('The Pope.', 'US'),
('Covering myself with Parmesan cheese and chili flakes because I am pizza.', 'US'),
('White people.', 'US'),
('The unstoppable tide of Islam.', 'US'),
('Unfathomable stupidity.', 'US'),
('A bird that shits human turds.', 'US'),
('Your weird brother.', 'US'),
('Jobs.', 'US'),
('Former President George W. Bush.', 'US'),
('Estrogen.', 'US'),
('Donald J. Trump.', 'US'),
('An AR-15 assault rifle.', 'US'),
('Casually suggesting a threesome.', 'US'),
('David Bowie flying in on a tiger made of lightning.', 'US'),
('Memes.', 'US'),
('A salty surprise.', 'US'),
('Balls.', 'US'),
('The Devil himself.', 'US'),
('Fucking the weatherman on live television.', 'US'),
('The female orgasm.', 'US'),
('Necrophilia.', 'US'),
('The magic of live theatre.', 'US'),
('Some punk kid who stole my turkey sandwich.', 'US'),
('Vomiting seafood and bleeding anally.', 'US'),
('Pulling out.', 'US'),
('Spectacular abs.', 'US'),
('Full frontal nudity.', 'US'),
('A tiny, gay guitar called a ukulele.', 'US'),
('Mansplaining.', 'US'),
('Poorly-timed Holocaust jokes.', 'US'),
('Sweet, sweet vengeance.', 'US'),
('How amazing it is to be on mushrooms.', 'US'),
('Lance Armstrong&apos;s missing testicle.', 'US'),
('Hope.', 'US'),
('The screams... the terrible screams.', 'US'),
('Gandhi.', 'US'),
('Only dating Asian women.', 'US'),
('Switching to Geico.&reg;', 'US'),
('Getting fingered.', 'US'),
('Yeast.', 'US'),
('Emotions.', 'US'),
('Crumbs all over the god damn carpet.', 'US'),
('A brain tumor.', 'US'),
('Wet dreams.', 'US'),
('Dark and mysterious forces beyond our control.', 'US'),
('Shaking a baby until it stops crying.', 'US'),
('Being on fire.', 'US'),
('Huge biceps.', 'US'),
('My vagina.', 'US'),
('Bill Nye the Science Guy.', 'US'),
('My inner demons.', 'US'),
('Pooping in a laptop and closing it.', 'US'),
('Battlefield amputations.', 'US'),
('A fetus.', 'US'),
('Strong female characters.', 'US'),
('Dry heaving.', 'US'),
('Tentacle porn.', 'US'),
('The Jews.', 'US'),
('The South.', 'US'),
('Teenage pregnancy.', 'US'),
('A pangender octopus who roams the cosmos in search of love.', 'US'),
('Saying &quot;I love you.&quot;', 'US'),
('Doin&apos; it in the butt.', 'US'),
('Synergistic management solutions.', 'US'),
('50,000 volts straight to the nipples.', 'US'),
('Self-loathing.', 'US'),
('Erectile dysfunction.', 'US'),
('Poopy diapers.', 'US'),
('Friction.', 'US'),
('A sassy black woman.', 'US'),
('Liberals.', 'US'),
('Oompa-Loompas.', 'US'),
('Drinking out of the toilet and eating garbage.', 'US'),
('Fragile masculinity.', 'US'),
('Kissing grandma on the forehead and turning off her life support.', 'US'),
('Rap music.', 'US'),
('GoGurt.&reg;', 'US'),
('The true meaning of Christmas.', 'US'),
('A pyramid of severed heads.', 'US'),
('Getting really high.', 'US'),
('Hot cheese.', 'US'),
('Incest.', 'US'),
('Elderly Japanese men.', 'US'),
('Announcing that I am about to cum.', 'US'),
('Invading Poland.', 'US'),
('RoboCop.', 'US'),
('Flying sex snakes.', 'US'),
('Slaughtering innocent civilians.', 'US'),
('Establishing dominance.', 'US'),
('Some guy.', 'US'),
('Girls.', 'US'),
('Italians.', 'US'),
('Shutting up so I can watch the game.', 'US'),
('Jennifer Lawrence.', 'US'),
('Blowing my boyfriend so hard he shits.', 'US'),
('A Mexican.', 'US'),
('The Underground Railroad.', 'US'),
('Penis envy.', 'US'),
('Repression.', 'US'),
('Cards Against Humanity.', 'US'),
('The Hustle.', 'US'),
('Jerking off into a pool of children&apos;s tears.', 'US'),
('Heteronormativity.', 'US'),
('A Bop It.&trade;', 'US'),
('Heartwarming orphans.', 'US'),
('The Great Depression.', 'US'),
('A falcon with a cap on its head.', 'US'),
('AXE Body Spray.', 'US'),
('Prescription pain killers.', 'US'),
('Solving problems with violence.', 'US'),
('Gloryholes.', 'US'),
('A homoerotic volleyball montage.', 'US'),
('This month&apos;s mass shooting.', 'US'),
('Radical Islamic terrorism.', 'US'),
('Flightless birds.', 'US'),
('A disappointing birthday party.', 'US'),
('Assless chaps.', 'US'),
('Vehicular manslaughter.', 'US'),
('Permanent Orgasm-Face Disorder.', 'US'),
('Boogers.', 'US'),
('The Blood of Christ.', 'US'),
('Cuddling.', 'US'),
('Looking in the mirror, applying lipstick, and whispering &quot;tonight, you will have sex with Tom Cruise.&quot;', 'US'),
('Authentic Mexican cuisine.', 'US'),
('The American Dream.', 'US'),
('Pooping back and forth. Forever.', 'US'),
('The Force.', 'US'),
('The only gay person in a hundred miles.', 'US'),
('Ethnic cleansing.', 'US'),
('Exactly what you&apos;d expect.', 'US'),
('Getting crushed by a vending machine.', 'US'),
('A ball of earwax, semen, and toenail clippings.', 'US'),
('Brown people.', 'US'),
('Steve Bannon.', 'US'),
('Diversity.', 'US'),
('Pixelated bukkake.', 'US'),
('Tearing that ass up like wrapping paper on Christmas morning.', 'US'),
('Sideboob.', 'US'),
('Seeing Grandma naked.', 'US'),
('Women in yogurt commercials.', 'US'),
('Arnold Schwarzenegger.', 'US'),
('The bombing of Nagasaki.', 'US'),
('Chainsaws for hands.', 'US'),
('Getting naked and watching Nickelodeon.', 'US'),
('Fear itself.', 'US'),
('The Trail of Tears.', 'US'),
('Swooping.', 'US'),
('Ghosts.', 'US'),
('My neck, my back, my pussy, and my crack.', 'US'),
('God.', 'US'),
('Nazis.', 'US'),
('MechaHitler.', 'US'),
('My collection of Japanese sex toys.', 'US'),
('One titty hanging out.', 'US'),
('Crippling debt.', 'US'),
('Passive aggressive Post-it notes.', 'US'),
('Whipping it out.', 'US'),
('Academy Award winner Meryl Streep.', 'US'),
('Funky fresh rhymes.', 'US'),
('How bad my daughter fucked up her dance recital.', 'US'),
('Fellowship in Christ.', 'US'),
('The violation of our most basic human rights.', 'US'),
('Coat hanger abortions.', 'US'),
('Morgan Freeman&apos;s voice.', 'US'),
('Stalin.', 'US'),
('8 oz. of sweet Mexican black-tar heroin.', 'US'),
('Old-people smell.', 'US'),
('Fake tits.', 'US'),
('Sexual tension.', 'US'),
('The inevitable heat death of the universe.', 'US'),
('A fuck-ton of almonds.', 'US'),
('Muhammad (Peace Be Upon Him).', 'US'),
('A really cool hat.', 'US'),
('An octopus giving seven handjobs and smoking a cigarette.', 'US'),
('These hoes.', 'US'),
('Listening to her problems without trying to solve them.', 'US'),
('The Russians.', 'US'),
('Waking up half-naked in a Denny&apos;s parking lot.', 'US'),
('Murder.', 'US'),
('A crucifixion.', 'US'),
('Her Majesty, Queen Elizabeth II.', 'US'),
('Not wearing pants.', 'US'),
('Man meat.', 'US'),
('A gossamer stream of jizz that catches the light as it arcs through the morning air.', 'US'),
('Lena Dunham.', 'US'),
('Many bats.', 'US'),
('Gay conversion therapy.', 'US'),
('Horse meat.', 'US'),
('The glass ceiling.', 'US'),
('Dick pics.', 'US'),
('Completely unwarranted confidence.', 'US'),
('One trillion dollars.', 'US'),
('Some of the best rappers in the game.', 'US'),
('Black people.', 'US'),
('Sperm whales.', 'US'),
('My sex life.', 'US'),
('Chemical weapons.', 'US'),
('A Fleshlight.&reg;', 'US'),
('Pictures of boobs.', 'US'),
('William Shatner.', 'US'),
('AIDS.', 'US'),
('Autocannibalism.', 'US'),
('A horde of Vikings.', 'US'),
('Danny DeVito.', 'US'),
('My abusive boyfriend who really isn&apos;t so bad once you get to know him.', 'US'),
('A three-way with my wife and Shaquille O&apos;Neal.', 'US'),
('Fiery poops.', 'US'),
('Lunchables.&trade;', 'US'),
('Meth.', 'US'),
('Soup that is too hot.', 'US'),
('Tap dancing like there&apos;s no tomorrow.', 'US'),
('Stephen Hawking talking dirty.', 'US'),
('Object permanence.', 'US'),
('The milkman.', 'US'),
('Braiding three penises into a Twizzler.', 'US'),
('My black ass.', 'US'),
('Kanye West.', 'US');


INSERT INTO `answers` (`answer`, `deck`)
VALUES 
('Poverty.', 'US'),
('Judging everyone.', 'US'),
('PTSD.', 'US'),
('Wondering if it&apos;s possible to get some of that salsa to go.', 'US'),
('Bitches.', 'US'),
('An icy handjob from an Edmonton hooker.', 'CA'),
('An Evening with Michael Bubl&eacute;.', 'CA'),
('Getting a DUI on a Zamboni.', 'CA'),
('The Royal Canadian Mounted Police.', 'CA'),
('Oestrogen.', 'CA'),
('Heritage minutes.', 'CA'),
('An endless stream of diarrhoea.', 'CA'),
('A hairless little shitstain named Caillou.', 'CA'),
('A despondent Maple Leafs fan sitting all alone.', 'CA'),
('Apologizing.', 'CA'),
('Syrupy sex with a maple tree.', 'CA'),
('An M16 assault rifle.', 'CA'),
('Canadian Netflix.', 'CA'),
('Punching an MP in the face.', 'CA'),
('Burning down the White House.', 'CA'),
('Newfies.', 'CA'),
('A vastly superior healthcare system.', 'CA'),
('Women of colour.', 'CA'),
('Living in Yellowknife.', 'CA'),
('A fuck-tonne of almonds.', 'CA'),
('Clubbing baby seals.', 'CA'),
('The only gay person in a hundred kilometers.', 'CA'),
('The Official Languages Act. La Loi sur les langues officielles.', 'CA'),
('Terry Fox&apos;s prosthetic leg.', 'CA'),
('Mr. Dressup.', 'CA'),
('Justin Trudeau.', 'CA'),
('Germans on holiday.', 'UK'),
('Sitting on my face.', 'UK'),
('The Hillsborough Disaster.', 'UK'),
('Queen Elizabeth&apos;s immaculate anus.', 'UK'),
('Druids.', 'UK'),
('The way James Bond treats women.', 'UK'),
('Blowing up Parliament.', 'UK'),
('A white van man.', 'UK'),
('Wanking into a pool of children&apos;s tears.', 'UK'),
('Benedict Cumberbatch.', 'UK'),
('Shitting out a perfect Cumberland sausage.', 'UK'),
('Shutting up so I can watch the match.', 'UK'),
('Faffing about.', 'UK'),
('Blood, toil, tears, and sweat.', 'UK'),
('Dirty nappies.', 'UK'),
('Catapult.', 'UK'),
('Your mum.', 'UK'),
('Dogging.', 'UK'),
('Concealing an erection.', 'UK'),
('Polish people.', 'UK'),
('Waking up in Idris Elba&apos;s arms.', 'UK'),
('A bleached arsehole.', 'UK'),
('Braiding three penises into a Curly Wurly.', 'UK'),
('Kissing nan on the forehead and turning off her life support.', 'UK'),
('However much weed &pound;20 can buy.', 'UK'),
('A Chelsea smile.', 'UK'),
('The EDL.', 'UK'),
('Being marginalised.', 'UK'),
('Ecstasy.', 'UK'),
('England.', 'UK'),
('The Black Death.', 'UK'),
('Jehovah&apos;s Witnesses.', 'UK'),
('Egging an MP.', 'UK'),
('The Scouts.', 'UK'),
('The end of days.', 'UK'),
('The North.', 'UK'),
('Maureen of Blackpool, Reader&apos;s Wife of the Year 1988.', 'UK'),
('Spaniards.', 'UK'),
('Forced sterilisation.', 'UK'),
('Some bloody peace and quiet.', 'UK'),
('A brain tumour.', 'UK'),
('Pikies.', 'UK'),
('An entrenched class system.', 'UK'),
('Just touching David Beckham&apos;s hair.', 'UK'),
('Used knickers.', 'UK'),
('A hen night in Slough.', 'UK'),
('Waking up half-naked in a Little Chef car park.', 'UK'),
('Paedophiles.', 'UK'),
('Haggis.', 'UK'),
('Anything that comes out of Prince Philip&apos;s mouth.', 'UK'),
('The bloody Welsh.', 'UK'),
('Mad cow disease.', 'UK'),
('The sudden appearance of the Go Compare man.', 'UK'),
('The smell of Primark.', 'UK'),
('Theresa May.', 'UK'),
('My mate Dave.', 'UK'),
('Cottaging.', 'UK'),
('Not wearing trousers.', 'UK'),
('A nice cup of tea.', 'UK'),
('Jimmy Savile.', 'UK'),
('Drinking out of the toilet and eating rubbish.', 'UK'),
('A posh wank.', 'UK'),
('A foul mouth.', 'UK'),
('Trench foot.', 'UK'),
('An AK-47 assault rifle.', 'UK'),
('A foetus.', 'UK'),
('Cheeky bum sex.', 'UK'),
('The Strictly Come Dancing season finale.', 'UK'),
('Bogies.', 'UK'),
('The Daily Mail.', 'UK'),
('A fanny fart.', 'UK'),
('Tories.', 'UK'),
('Perfunctory foreplay.', 'UK'),
('Slapping Nigel Farage over and over.', 'UK'),
('Madeleine McCann.', 'UK'),
('400 years of colonial atrocities.', 'UK'),
('Queuing.', 'UK'),
('Passive-aggressive Post-it notes.', 'UK'),
('LYNX&reg; Body Spray.', 'UK'),
('9 oz. of sweet Mexican black-tar heroin.', 'UK'),
('Crumbs all over the bloody carpet.', 'UK'),
('Chivalry.', 'UK'),
('Amputees.', 'UK'),
('A bit of slap and tickle.', 'UK'),
('Seeing Granny naked.', 'UK'),
('Sniffing glue.', 'UK'),
('The petty troubles of the landed gentry.', 'UK'),
('Lads.', 'UK'),
('The French.', 'UK'),
('Ed Balls.', 'UK'),
('A vindaloo poo.', 'UK'),
('Scousers.', 'UK'),
('Getting naked and watching CBeebies.', 'UK'),
('Rubbing Boris Johnson&apos;s belly until he falls asleep.', 'UK'),
('A sober Irishman who doesn&apos;t care for potatoes.', 'UK'),
('Daddies&reg; Brown Sauce.', 'UK'),
('Brexit.', 'UK'),
('Knife crime.', 'UK'),
('Getting married, having a few kids, buying some stuff, retiring to the south of France, and dying.', 'UK'),
('Africa children.', 'UK'),
('Somali pirates.', 'UK'),
('Hooning.', 'AU'),
('Waking up half-naked in a Macca&apos;s car park.', 'AU'),
('Half a kilo of pure China White heroin.', 'AU'),
('100% Pure New Zealand.', 'AU'),
('Pauline Hanson.', 'AU'),
('Skippy the Bush Kangaroo.', 'AU'),
('A slab of VB and a pack of durries.', 'AU'),
('Winking at old people.', 'AU'),
('Getting married, having a few kids, buying some stuff, retiring to Queensland, and dying.', 'AU'),
('Fiery poos.', 'AU'),
('Having a Golden Gaytime.', 'AU'),
('Total control of the media.', 'AU'),
('All four prongs of an echidna&apos;s penis.', 'AU'),
('The White Australia Policy.', 'AU'),
('Making up for centuries of oppression with one day of apologising.', 'AU'),
('Glassing a wanker.', 'AU'),
('Dropping a baby down the dunny.', 'AU'),
('A sick burnout.', 'AU'),
('Rupert Murdoch.', 'AU'),
('Women in yoghurt commercials.', 'AU'),
('Tony Abbott in budgie smugglers.', 'AU'),
('Contagious face cancer.', 'AU'),
('Mr. Squiggle, the Man from the Moon.', 'AU'),
('Taking a sheep-wife.', 'AU'),
('Crazy hot cousin sex.', 'AU'),
('Getting so angry that you pop a stiffy.', 'AU'),
('Nothing but sand.', 'AU'),
('A cute, fuzzy koala with chlamydia.', 'AU'),
('Profound respect and appreciation for indigenous culture.', 'AU'),
('John Howard&apos;s eyebrows.', 'AU'),
('Selling ice to children.', 'AU'),
('A sick wombat.', 'AU'),
('A Halal Snack Pack.', 'AU'),
('Braiding three penises into a licorice twist.', 'AU'),
('The cool, refreshing taste of Coca-Cola.&reg;', 'AU'),
('Getting naked and watching Play School.', 'AU'),
('Women&apos;s undies.', 'AU'),
('Nippers.', 'AU'),
('Summoning Harold Holt from the sea in a time of great need.', 'AU'),
('A didgeridildo.', 'AU'),
('A five-litre goon bag.', 'AU'),
('Vegemite.&trade;', 'AU'),
('Good-natured, fun-loving Aussie racism.', 'AU'),
('A fair go.', 'AU'),
('Cashed-up bogans.', 'AU'),
('Inserting a jam jar into my anus.', 'AU'),
('Doin&apos; it up the bum.', 'AU'),
('A stingray barb through the chest.', 'AU'),
('Pingers.', 'AU'),
('The bush.', 'AU'),
('Sorry, this content cannot be viewed in your region.', 'AU'),
('A shark!', 'AU'),
('Americanization.', 'AU'),
('Having a shag in the back of a ute.', 'AU'),
('Australia.', 'AU'),
('Massive, widespread drought.', 'AU'),
('Millions of cane toads.', 'AU'),
('Alcohol poisoning.', 'AU'),
('Xenophobia.', 'AU'),
('Ice.', 'AU'),
('A decent fucking Internet connection.', 'AU'),
('What&apos;s left of the Great Barrier Reef.', 'AU'),
('The Hemsworth brothers.', 'AU'),
('A literal tornado of fire.', 'AU'),
('The Great Emu War.', 'AU'),
('Chundering into a kangaroo&apos;s pouch.', 'AU'),
('The big fucking hole in the ozone layer.', 'AU'),
('My cheating prick of a husband.', 'AU'),
('Denying climate change.', 'AU'),
('Whiskas&reg; Catmilk.', 'AU'),
('Steve Irwin.', 'AU'),
('Chunks of dead backpacker.', 'AU'),
('The inevitable heath death of the universe.', 'AU'),
('A six-point plan to stop the boats.', 'AU'),
('Whoever the Prime Minister is these days.', 'AU'),
('An ass disaster.', 'INTL'),
('Disco fever.', 'INTL'),
('Words.', 'INTL'),
('Spending lots of money.', 'INTL'),
('Mooing.', 'INTL'),
('A cat video so cute that your eyes roll back and your spine slides out of your anus.', 'INTL'),
('Michael Jackson.', 'INTL'),
('Horrifying laser hair removal accidents.', 'INTL'),
('Dying alone and in pain.', 'INTL'),
('Shitting out a screaming face.', 'INTL'),
('Literally eating shit.', 'INTL'),
('A monkey smoking a cigar.', 'INTL'),
('Rich people.', 'INTL'),
('An evil man in evil clothes.', 'INTL'),
('A low standard of living.', 'INTL'),
('Wearing an octopus for a hat.', 'INTL'),
('Whining like a little bitch.', 'INTL'),
('Not having sex,', 'INTL'),
('A fat bald man from the Internet.', 'INTL'),
('Basic human decency.', 'INTL'),
('How awesome it is to be white.', 'INTL'),
('Nothing.', 'INTL'),
('Doing it in the butt.', 'INTL'),
('Moral ambiguity.', 'INTL'),
('Dining with cardboard cutouts of the cast of Friends.', 'INTL'),
('A big black dick.', 'INTL'),
('The arrival of pizza.', 'INTL'),
('An unstoppable wave of fire ants.', 'INTL'),
('Extremely tight jeans.', 'INTL'),
('A web of lies.', 'INTL'),
('Ominous background music.', 'INTL'),
('My machete.', 'INTL'),
('Multiple orgasms.', 'INTL'),
('Daddy&apos;s belt.', 'INTL'),
('Eating a hard boiled out of my husband&apos;s asshole.', 'INTL'),
('Friendly fire.', 'INTL'),
('The boners of the elderly.', 'INTL'),
('The hiccups.', 'INTL'),
('The crazy, ball-slapping sex your parents are having right now.', 'INTL'),
('Going around punching people.', 'INTL'),
('Letting everyone down.', 'INTL'),
('Nunchuck moves.', 'INTL'),
('The prunes I&apos;ve been saving for you in my armpits.', 'INTL'),
('A PowerPoint presentation.', 'INTL'),
('The entire Internet.', 'INTL'),
('An AK-47.', 'INTL'),
('Walking in on Dad peeing into Mom&apos;s mouth.', 'INTL'),
('Dad&apos;s funny balls.', 'INTL'),
('Flying robots that kill people.', 'INTL'),
('Weapons-grade plutonium.', 'INTL'),
('Sexy pillow fights.', 'INTL'),
('Being white.', 'INTL'),
('A slightly shittier parallel universe.', 'INTL'),
('Having sex on top of a pizza.', 'INTL'),
('Power.', 'INTL'),
('Scrotum tickling.', 'INTL'),
('An army of skeletons.', 'INTL'),
('Actually getting shot, for real.', 'INTL'),
('A cop who is also a dog.', 'INTL'),
('A vagina that leads to another dimension.', 'INTL'),
('A man in yoga pants with a ponytail and feather earrings.', 'INTL'),
('Converting to Islam.', 'INTL'),
('Me.', 'INTL'),
('Tom Cruise.', 'INTL'),
('Intimacy problems.', 'INTL'),
('Leveling up.', 'INTL'),
('That ass.', 'INTL'),
('Kim Jong-un.', 'INTL'),
('The Dalai Lama.', 'INTL'),
('Ripping open a man&apos;s chest and pulling out his still-beating heart.', 'INTL'),
('A sad fat dragon with no friends.', 'INTL'),
('A surprising amount of hair.', 'INTL'),
('Some really fucked-up shit.', 'INTL'),
('Robert Downey Jr.', 'INTL'),
('Ryan Gosling riding in on a white horse.', 'INTL'),
('Sexual humiliation.', 'INTL'),
('Fisting.', 'INTL'),
('The human body.', 'INTL'),
('A defective condom.', 'INTL'),
('My father, who died when I was seven.', 'INTL'),
('The economy.', 'INTL'),
('Deflowering the princess.', 'INTL'),
('A Chinese tourist who wants something very badly but cannot communicate it.', 'INTL'),
('Graphic violence, adult language, and some sexual content.', 'INTL'),
('Self-flagellation.', 'INTL'),
('Shutting the fuck up.', 'INTL'),
('FIlling my son with spaghetti.', 'INTL'),
('The baby that ruined my pussy.', 'INTL'),
('Buying the right clothes to be cool.', 'INTL'),
('Being black.', 'INTL'),
('All of this blood.', 'INTL'),
('Edible underwear.', 'INTL'),
('An oversized lollipop,', 'INTL'),
('Stockholm Syndrome.', 'INTL'),
('The World of Warcraft.', 'INTL'),
('Grave robbing.', 'INTL'),
('Gandalf.', 'INTL'),
('Sneezing, farting, and cumming at the same time.', 'INTL'),
('Running naked through a mall, pissing and shitting everywhere.', 'INTL'),
('Blood farts.', 'INTL'),
('Panda sex.', 'INTL'),
('A thermonuclear detonation.', 'INTL'),
('Destroying the evidence.', 'INTL'),
('Vomiting mid-blowjob.', 'INTL'),
('A pi&ntilde;ata full of scorpions.', 'INTL'),
('Miley Cyrus.', 'INTL'),
('A Japanese toaster you can fuck.', 'INTL'),
('Suicidal thoughts.', 'INTL'),
('Grandpa&apos;s ashes.', 'INTL'),
('Reverse cowgirl.', 'INTL'),
('Keanu Reeves.', 'INTL'),
('LIving in a trashcan.', 'INTL'),
('My first kill.', 'INTL'),
('Mom.', 'INTL'),
('Children on leashes.', 'INTL'),
('Double penetration.', 'INTL'),
('Slave.', 'INTL'),
('White power.', 'INTL'),
('Indescribable loneliness.', 'INTL'),
('Tongue.', 'INTL'),
('Tiny nipples.', 'INTL'),
('Being fabulous.', 'INTL'),
('Homeless people.', 'INTL'),
('My cheating-son-of-a-bitch-husband.', 'INTL'),
('Screaming like a maniac.', 'INTL'),
('Heroin.', 'INTL'),
('Existing.', 'INTL'),
('The pirate&apos;s life.', 'INTL'),
('One Ring to rule them all.', 'INTL'),
('The flute.', 'INTL'),
('Being a busy adult with many important things to do.', 'INTL'),
('Slapping a racist old lady.', 'INTL'),
('Genetically engineered super-soldiers.', 'INTL'),
('Pumping out a baby every nine months.', 'INTL'),
('A mime having a stroke.', 'INTL'),
('Women voting.', 'INTL'),
('Gladiatorial combat.', 'INTL'),
('Some kind of bird man.', 'INTL'),
('Taking a man&apos;s eyes and balls out and putting his eyes where his balls go and then his balls in the eye holes.', 'INTL'),
('Mild autism.', 'INTL'),
('Rising from the grave.', 'INTL'),
('Not contributing to society in any meaningful way.', 'INTL'),
('Cock.', 'INTL'),
('Some douche with an acoustic guitar.', 'INTL'),
('Terrorists.', 'INTL'),
('Overpowering your father.', 'INTL'),
('Being a hideous beast that no one could love.', 'INTL'),
('Samuel L. Jackson.', 'INTL'),
('Making the penises kiss.', 'INTL'),
('Being a dinosaur.', 'INTL'),
('Staring at a painting and going &quot;hmmmmmmm...&quot;', 'INTL'),
('A sweet spaceships.', 'INTL'),
('Lady Gaga.', 'INTL'),
('Tripping balls.', 'INTL'),
('Eating an albino.', 'INTL'),
('Our first chimpanzee Prime Minister.', 'INTL'),
('Sudden Poop Explosion Disease.', 'INTL'),
('The total collapse of the global financial system.', 'INTL'),
('Loki, the trickster god.', 'INTL'),
('Making a friend.', 'INTL'),
('The Gulags.', 'INTL'),
('Hipsters.', 'INTL'),
('Wiping her butt.', 'INTL'),
('All my friends dying.', 'INTL'),
('The land of chocolate.', 'INTL'),
('Jesus.', 'INTL'),
('Another shot of morphine.', 'INTL'),
('Bosnian chicken farmers.', 'INTL'),
('How wet my pussy is.', 'INTL'),
('Having shotguns for legs.', 'INTL'),
('Bullshit.', 'INTL'),
('Blowing my boyfriend so hard so he shits.', 'INTL'),
('Cumming deep inside my best bro.', 'INTL'),
('Being awesome at sex.', 'INTL'),
('Santa Claus.', 'INTL'),
('Having a penis.', 'INTL'),
('Gay aliens.', 'INTL'),
('Jafar.', 'RED'),
('Jumping out at people.', 'RED'),
('The mixing of the races.', 'RED'),
('The Harlem Globetrotters.', 'RED'),
('Scrotal frostbite.', 'RED'),
('Statistically validated stereotypes.', 'RED'),
('Pretty Pretty Princess Dress-Up Board Game.&reg;', 'RED'),
('Making shit up.', 'RED'),
('Mufasa&apos;s death scene.', 'RED'),
('Having $57 in the bank.', 'RED'),
('A sales team of clowns and pedophiles.', 'RED'),
('Survivor&apos;s guilt.', 'RED'),
('The mere concept of Applebees.&reg;', 'RED'),
('Boris the Soviet Love Hammer.', 'RED'),
('Not having sex.', 'RED'),
('Indescribably loneliness.', 'RED'),
('One thousand Slim Jims.', 'RED'),
('A nuanced critique.', 'RED'),
('A nautical theme.', 'RED'),
('The black Power Ranger.', 'RED'),
('Neil Patrick Harris.', 'RED'),
('Bill Clinton, naked on a bearskin rug with a saxophone.', 'RED'),
('The hose.', 'RED'),
('Finding Waldo.', 'RED'),
('Fuck Mountain.', 'RED'),
('Unlimited soup, salad, and breadsticks.', 'RED'),
('Syphilitic insanity.', 'RED'),
('Oncoming traffic.', 'RED'),
('Suicide bombers.', 'RED'),
('Some kind of bird-man.', 'RED'),
('Ryan Goslin riding in on a white horse.', 'RED'),
('Living in a trash can.', 'RED'),
('Historical revisionism.', 'RED'),
('A passionate Latino lover.', 'RED'),
('Roland the Farter, flatulist to the king.', 'RED'),
('Consent.', 'RED'),
('An unhinged Ferris wheel rolling toward the sea.', 'RED'),
('A plunger to the face.', 'RED'),
('Shaft.', 'RED'),
('Big Bird&apos;s crown, crusty asshole.', 'RED'),
('Filling every orifice with butterscotch pudding.', 'RED'),
('A fortuitous turnip harvest.', 'RED'),
('Buying the right pants to be cool.', 'RED'),
('Getting hilariously gang-banged by the Blue Man Group.', 'RED'),
('A phantasmagoria of anal delights.', 'RED'),
('The new Radiohead album.', 'RED'),
('24-hour media coverage.', 'RED'),
('Gargling jizz.', 'RED'),
('A dollop of sour cream.', 'RED'),
('Demonic possession.', 'RED'),
('Chugging a lava lamp.', 'RED'),
('Jeff Goldblum.', 'RED'),
('The day the birds attacked.', 'RED'),
('Subduing a grizzly bear and making her your wife.', 'RED'),
('A sofa that says &quot;I have style, but I like to be comfortable.&quot;', 'RED'),
('Dorito breath.', 'RED'),
('The way white people is.', 'RED'),
('Fetal alcohol syndrome.', 'RED'),
('The Quesadilla Explosion Salad&trade; from Chili&apos;s.&reg;', 'RED'),
('Racial profiling.', 'RED'),
('Special musical guest, Cher.', 'RED'),
('A crappy little hand.', 'RED'),
('The systemic destruction of an entire people and their way of life.', 'RED'),
('Clenched butt cheeks.', 'RED'),
('Filing my son with spaghetti.', 'RED'),
('Blowing some dudes in an alley.', 'RED'),
('Words, words, words.', 'RED'),
('Clams.', 'RED'),
('Hot doooooooogs!', 'RED'),
('Andr&eacute; the Giant&apos;s enormous, leathery scrotum.', 'RED'),
('A greased-up Matthew McConaughey.', 'RED'),
('A pile of squirming bodies.', 'RED'),
('A bloody pacifier.', 'RED'),
('Medieval Times&reg; Dinner &amp; Tournament.', 'RED'),
('Just the tip.', 'RED'),
('One ring to rule them all.', 'RED'),
('The milk that comes out of a person.', 'RED'),
('A sweet spaceship.', 'RED'),
('Big ol&apos; floppy titties.', 'RED'),
('A 55-gallon drum of lube.', 'RED'),
('Sorcery.', 'RED'),
('Getting your dick stuck in a Chinese finger trap with another dick.', 'RED'),
('Weapons grade plutonium.', 'RED'),
('Mad hacky-sack skills.', 'RED'),
('Emotional baggage.', 'RED'),
('Insatiable bloodlust.', 'RED'),
('Hillary Clinton.', 'RED'),
('Catastrophic urethral trauma.', 'RED'),
('Putting an entire peanut butter and jelly sandwich into the VCR.', 'RED'),
('Crying into the pages of Sylvia Plath.', 'RED'),
('A spontaneous conga line.', 'RED'),
('A Japanese tourist who wants something very badly but cannot communicate it.', 'RED'),
('A boo-boo.', 'RED'),
('A black-owned and operated business.', 'RED'),
('The moist, demanding chasm of his mouth.', 'RED'),
('Velcro.&trade;', 'RED'),
('The shambling corpse of Larry King.', 'RED'),
('Drinking my bro&apos;s pee-pee right out of his peen.', 'RED'),
('Quiche.', 'RED'),
('Some really fucked up shit.', 'RED'),
('Warm, velvety muppet sex.', 'RED'),
('The primal, ball-slapping sex your parents are having right now.', 'RED'),
('A bigger, blacker dick.', 'RED'),
('Crabapples all over the fucking sidewalk.', 'RED'),
('Bosnian chick farmers.', 'RED'),
('Sanding off a man&apos;s nose.', 'RED'),
('The harsh light of day.', 'RED'),
('Vietnam flashbacks.', 'RED'),
('Savagely beating a mascot.', 'RED'),
('Staring at a painting and going &quot;hmmmmmm...&quot;', 'RED'),
('Nubile slave boys.', 'RED'),
('Drinking ten 5-hour ENERGYs&reg; to get fifty continuous hours of energy.', 'RED');

INSERT INTO `answers` (`answer`, `deck`)
VALUES 
('A sweaty, panting leather daddy.', 'RED'),
('My manservant, Claude.', 'RED'),
('Khakis.', 'BLUE'),
('Bathing in moonsblood and dancing around the ancient oak.', 'BLUE'),
('The passage of time.', 'BLUE'),
('A one-way ticket to Gary, Indiana.', 'BLUE'),
('The power of the Dark Side.', 'BLUE'),
('A team of lawyers.', 'BLUE'),
('Getting eaten alive by Guy Fieri.', 'BLUE'),
('Figuring out how to have sex with a dolphin.', 'BLUE'),
('Some sort of Asian.', 'BLUE'),
('Vegetarian options.', 'BLUE'),
('An inability to form meaningful relationships.', 'BLUE'),
('One unforgettable night of passion.', 'BLUE'),
('Important news about Taylor Swift.', 'BLUE'),
('The all-new Nissan Pathfinder with 0.9% APR financing!', 'BLUE'),
('Free ice cream, yo.', 'BLUE'),
('My boyfriend&apos;s stupid penis.', 'BLUE'),
('A mouthful of potato salad.', 'BLUE'),
('Our new Buffalo Chicken Dippers&reg;!', 'BLUE'),
('Crying and shitting and eat spaghetti.', 'BLUE'),
('A fart.', 'BLUE'),
('Actual mutants with medical conditions and no superpowers.', 'BLUE'),
('Deez nuts.', 'BLUE'),
('Africa.', 'BLUE'),
('Finally finishing off the Indians.', 'BLUE'),
('Owls, the perfect predator.', 'BLUE'),
('A dance move that&apos;s just sex.', 'BLUE'),
('Ass to mouth.', 'BLUE'),
('Bouncing up and down.', 'BLUE'),
('Walking into a glass door.', 'BLUE'),
('Eating together like a god damn family for once.', 'BLUE'),
('No longer finding any Cards Against Humanity card funny.', 'BLUE'),
('Treasures beyond your wildest dreams.', 'BLUE'),
('Ejaculating live bees and the bees are angry.', 'BLUE'),
('Sucking all the milk out of a yak.', 'BLUE'),
('Falling into the toilet.', 'BLUE'),
('The color &quot;puce.&quot;', 'BLUE'),
('An oppressed people with a vibrant culture.', 'BLUE'),
('Out-of-this-world bazongas.', 'BLUE'),
('Getting caught by the police and going to jail.', 'BLUE'),
('The sweet song of sword against sword and the braying of mighty war beasts.', 'BLUE'),
('A sex goblin with a carnival penis.', 'BLUE'),
('Genghis Khan&apos;s DNA.', 'BLUE'),
('A gender identity that can only be conveyed through slam poetry.', 'BLUE'),
('The ghost of Marlon Brando.', 'BLUE'),
('Immortality cream.', 'BLUE'),
('Butt stuff.', 'BLUE'),
('Getting offended.', 'BLUE'),
('My dad&apos;s dumb fucking face.', 'BLUE'),
('A bunch of idiots playing a card game instead of interacting like normal humans.', 'BLUE'),
('Neil Diamond&apos;s Greatest Hits.', 'BLUE'),
('Whatever a McRib&reg; is made of.', 'BLUE'),
('Total fucking chaos.', 'BLUE'),
('Whispering all sexy.', 'BLUE'),
('Calculating every mannerism so as not to suggest homosexuality.', 'BLUE'),
('Some shit-hot guitar licks.', 'BLUE'),
('No clothes on, penis in vagina.', 'BLUE'),
('Sports.', 'BLUE'),
('How awesome I am.', 'BLUE'),
('The white half of Barack Obama.', 'BLUE'),
('An overwhelming variety of cheeses.', 'BLUE'),
('Ejaculating inside another man&apos;s wife.', 'BLUE'),
('Getting shot by the police.', 'BLUE'),
('Beloved television star Bill Cosby.', 'BLUE'),
('The tiger that killed my father.', 'BLUE'),
('Changing a person&apos;s mind with logic and facts.', 'BLUE'),
('Child Protective Services.', 'BLUE'),
('A peyote-fueled vision quest.', 'BLUE'),
('Cute boys.', 'BLUE'),
('A hopeless amount of spiders.', 'BLUE'),
('The swim team, all at once.', 'BLUE'),
('Whatever you wish, mother.', 'BLUE'),
('A possible Muslim.', 'BLUE'),
('All the single ladies.', 'BLUE'),
('Letting out 20 years&apos; worth of farts.', 'BLUE'),
('Being paralyzed from the neck down.', 'BLUE'),
('The eight gay warlocks who dictate the rules of fashion.', 'BLUE'),
('Shapes and colors.', 'BLUE'),
('Seeing my village burned and my family slaughtered before my eyes.', 'BLUE'),
('Filling a man&apos;s anus with concrete.', 'BLUE'),
('Peeing into a girl&apos;s butt to make a baby.', 'BLUE'),
('Meaningless sex.', 'BLUE'),
('Wearing glasses and sounding smart.', 'BLUE'),
('Setting my balls on fire and cartwheeling to Ohio.', 'BLUE'),
('Child support payments.', 'BLUE'),
('Being John Malkovich.', 'BLUE'),
('Throwing stones at a man until he dies.', 'BLUE'),
('A shiny rock that proves I love you.', 'BLUE'),
('Kale.', 'BLUE'),
('Stuffing a child&apos;s face with Fun Dip&reg; until he starts having fun.', 'BLUE'),
('A turd.', 'BLUE'),
('Party Mexicans.', 'BLUE'),
('Too much cocaine.', 'BLUE'),
('Like a million alligators.', 'BLUE'),
('Grammar nazis who are also regular Nazis.', 'BLUE'),
('A face full of horse cum.', 'BLUE'),
('Fresh dill from the patio.', 'BLUE'),
('Boring vaginal sex.', 'BLUE'),
('Crazy opium eyes.', 'BLUE'),
('AIDS monkeys.', 'BLUE'),
('Crippling social anxiety.', 'BLUE'),
('Not believing in giraffes.', 'BLUE'),
('An interracial handshake.', 'BLUE'),
('Irrefutable evidence that God is real.', 'BLUE'),
('A zero-risk way to make $2,000 from home.', 'BLUE'),
('My sex dungeon.', 'BLUE'),
('Being nine years old.', 'BLUE'),
('Daddy.', 'BLUE'),
('Unquestioning obedience.', 'BLUE'),
('A bass drop so huge it tears the starry vault asunder to reveal the face of God.', 'BLUE'),
('Sharks with legs.', 'BLUE'),
('Generally having no idea what&apos;s going on.', 'BLUE'),
('Bullets.', 'BLUE'),
('An unforgettable quincea&ntilde;era.', 'BLUE'),
('Two whales fucking the shit out of each other.', 'BLUE'),
('A whole lotta woman.', 'BLUE'),
('A self-microwaving burrito.', 'BLUE'),
('Snorting coke off a clown&apos;s boner.', 'BLUE'),
('A buttload of candy.', 'BLUE'),
('A thrilling chase over the rooftops of Rio de Janeiro.', 'BLUE'),
('Dem titties.', 'BLUE'),
('The amount of gay I am.', 'BLUE'),
('My first period.', 'BLUE'),
('Common-sense gun control legislation.', 'BLUE'),
('Being a terrible mother.', 'BLUE'),
('Being popular and good at sports.', 'BLUE'),
('Never having sex again.', 'BLUE'),
('A giant powdery manbaby.', 'BLUE'),
('A crazy little thing called love.', 'BLUE'),
('Stupid.', 'BLUE'),
('The best taquito in the galaxy.', 'BLUE'),
('Fucking a corpse back to life.', 'BLUE'),
('A pizza guy who fucked up.', 'BLUE'),
('Ennui.', 'BLUE'),
('Injecting speed into one arm and horse tranquilizer into the other.', 'BLUE'),
('Lots and lots of abortions.', 'BLUE'),
('Eggs.', 'BLUE'),
('My worthless son.', 'BLUE'),
('Blowjobs for everyone.', 'BLUE'),
('Critical thinking.', 'GREEN'),
('Shitting all over the floor like a bad, bad girl.', 'BLUE'),
('An uninterrupted history of imperialism and exploitation.', 'BLUE'),
('The unbelievable world of mushrooms.', 'BLUE'),
('A horse with no legs.', 'BLUE'),
('Having been dead for a while.', 'BLUE'),
('Drinking responsibly.', 'BLUE'),
('Breastfeeding a ten-year-old.', 'BLUE'),
('Going to a high school reunion on ketamine.', 'BLUE'),
('Backwards knees.', 'BLUE'),
('Gwyneth Paltrow&apos;s opinions.', 'BLUE'),
('The basic suffering that pervades all of existence.', 'BLUE'),
('Cutting off a flamingo&apos;s legs with garden shears.', 'BLUE'),
('The secret formula for ultimate female satisfaction.', 'BLUE'),
('Seeing things from Hitler&apos;s perspective.', 'BLUE'),
('A constant need for validation.', 'BLUE'),
('Jizz.', 'BLUE'),
('What Jesus would do.', 'BLUE'),
('A Ugandan warlord.', 'BLUE'),
('Slowly easing down onto a cucumber.', 'BLUE'),
('Smoking crack, for instance.', 'BLUE'),
('A kiss on the lips.', 'BLUE'),
('The haunting stare of an Iraqi child.', 'BLUE'),
('A sex comet from Neptune that plunges the Earth into eternal sexiness.', 'BLUE'),
('Giant sperm from outer space.', 'BLUE'),
('The euphoric rush of strangling a drifter.', 'BLUE'),
('Morpheus.', 'BLUE'),
('Mom&apos;s new boyfriend.', 'BLUE'),
('Blackface.', 'BLUE'),
('Every ounce of charisma left in Mick Jagger&apos;s tired body.', 'BLUE'),
('Sudden penis loss.', 'BLUE'),
('Daddy&apos;s credit card.', 'BLUE'),
('Ripping a dog in half.', 'BLUE'),
('Angelheaded hipsters burning for the ancient heavenly connection to the starry dynamo in the machinery of the night.', 'BLUE'),
('Interspecies marriage.', 'BLUE'),
('Cancer.', 'BLUE'),
('The male gaze.', 'BLUE'),
('Being worshipped as the one true God.', 'BLUE'),
('All these decorative pillows.', 'BLUE'),
('Unrelenting genital punishment.', 'BLUE'),
('Exploding pigeons.', 'BLUE'),
('A disappointing salad.', 'BLUE'),
('The dentist.', 'BLUE'),
('Moderate-to-severe joint pain.', 'BLUE'),
('Getting drive-by shot.', 'BLUE'),
('The black half of Barack Obama.', 'BLUE'),
('Western standards of beauty.', 'BLUE'),
('A reason not to commit suicide.', 'BLUE'),
('40 acres and a mule.', 'BLUE'),
('Such a big boy.', 'BLUE'),
('10 Incredible Facts About the Anus.', 'BLUE'),
('A manhole.', 'BLUE'),
('The size of my penis.', 'BLUE'),
('The complex geopolitical quagmire that is the Middle East.', 'BLUE'),
('My dead son&apos;s baseball glove.', 'BLUE'),
('Robots who just want to party.', 'BLUE'),
('A whole new kind of porn.', 'BLUE'),
('Ambiguous sarcasm.', 'BLUE'),
('Russian super-tuberculosis.', 'BLUE'),
('Prince Ali, fabulous he, Ali Ababwa.', 'BLUE'),
('Doing the right stuff to her nipples.', 'BLUE'),
('Ancient Athenian boy-fucking.', 'BLUE'),
('The eighth graders.', 'BLUE'),
('September 11th, 2001.', 'BLUE'),
('The safe word.', 'BLUE'),
('Doo-doo.', 'BLUE'),
('Blackula.', 'BLUE'),
('Anal fissures like you wouldn&apos;t believe.', 'BLUE'),
('Texas.', 'BLUE'),
('Going down on a woman, discovering that her vaginas is filled with eyeballs, and being totally into that.', 'BLUE'),
('P.F. Chang himself.', 'BLUE'),
('Almost giving money to a homeless person.', 'BLUE'),
('Depression.', 'BLUE'),
('Growing up chained to a radiator in perpetual darkness.', 'BLUE'),
('Three consecutive seconds of happiness.', 'BLUE'),
('Going inside at some point because of the mosquitoes.', 'BLUE'),
('Pussy.', 'BLUE'),
('Unsheathing my massive horse cock.', 'BLUE'),
('A woman.', 'BLUE'),
('Turning the rivers red with the blood of infidels.', 'BLUE'),
('A woman who is so cool that he rides on a motorcycle.', 'BLUE'),
('The peaceful and nonthreatening rise of China.', 'BLUE'),
('A chimpanzee in sunglasses fucking your wife.', 'BLUE'),
('Finding a nice elevator to poop in.', 'GREEN'),
('An incurable homosexual.', 'GREEN'),
('The body of a 46-year-old man.', 'GREEN'),
('Mixing M&amp;Ms and Skittles like some kind of psychopath.', 'GREEN'),
('Grunting for ten minutes and then peeing sand.', 'GREEN'),
('Gay thoughts.', 'GREEN'),
('When the big truck goes &quot;Toot! Toot!&quot;', 'GREEN'),
('Water.', 'GREEN'),
('Becoming the President of the United States.', 'GREEN'),
('Hot lettuce.', 'GREEN'),
('Rock-hard tits and a huge vagina.', 'GREEN'),
('Meatloaf, the man.', 'GREEN'),
('Smashing my balls at the moment of climax.', 'GREEN'),
('A creature made of penises that must constantly arouse itself to survive.', 'GREEN'),
('My brother&apos;s hot friends.', 'GREEN'),
('You.', 'GREEN'),
('Getting high with mom.', 'GREEN'),
('Twisting my cock and balls into a balloon poodle.', 'GREEN'),
('Loud, scary thunder.', 'GREEN'),
('Whomsoever let the dogs out.', 'GREEN'),
('Having a vagina.', 'GREEN'),
('A man with the head of a goat and the body of a goat.', 'GREEN'),
('Taking the form of a falcon.', 'GREEN'),
('A hug.', 'GREEN'),
('Putting more black people in jail.', 'GREEN'),
('Trevor, the world&apos;s greatest boyfriend.', 'GREEN'),
('Anal.', 'GREEN'),
('Just now finding out about the Armenian Genocide.', 'GREEN'),
('Getting the Dorito crumbs out of my pubes.', 'GREEN'),
('A man in a suit with perfect hair who tells you beautiful lies.', 'GREEN'),
('Quacking like a duck in lieu of a cogent argument.', 'GREEN'),
('A long business meeting with no obvious purpose.', 'GREEN'),
('Facilitating dialogue and deconstructing binaries.', 'GREEN'),
('Getting killed and dragged up a tree by a leopard.', 'GREEN'),
('Brunch.', 'GREEN'),
('Child labor.', 'GREEN'),
('Esmeralda, my most beautiful daughter.', 'GREEN'),
('The feeling of going to McDonald&apos;s as a 6-year-old.', 'GREEN'),
('Eating people.', 'GREEN'),
('Art.', 'GREEN'),
('Having sex with your mom.', 'GREEN'),
('The hottest MILF in Dallas.', 'GREEN'),
('Getting trapped in a conversation about Ayn Rand.', 'GREEN'),
('Happy daddies with happy sandals.', 'GREEN'),
('A dolphin that learns to talk and becomes the Dead of Harvard Law School.', 'GREEN'),
('The graceful path of an autumn leaf as it falls to its earthen cradle.', 'GREEN'),
('Meatloaf, the food.', 'GREEN'),
('10,000 shrieking teenage girls.', 'GREEN'),
('Chris Hemsworth.', 'GREEN'),
('Straight blazin&apos; 24/7.', 'GREEN'),
('Objectifying women.', 'GREEN'),
('The mysterious fog rolling into town.', 'GREEN'),
('Math.', 'GREEN'),
('Restoring Germany to its former glory.', 'GREEN'),
('Exploring each other&apos;s buttholes.', 'GREEN'),
('An old dog full of tumors.', 'GREEN'),
('Antidepressants.', 'GREEN'),
('Having an awesome time drinking and driving.', 'GREEN'),
('Jazz.', 'GREEN'),
('Dumpster juice.', 'GREEN'),
('Raising three kids on minimum wage.', 'GREEN'),
('Going to bed at a reasonable hour.', 'GREEN'),
('10 football players with erections barreling towards you at full speed.', 'GREEN'),
('Working so hard to have muscles and then having them.', 'GREEN'),
('Turning 32.', 'GREEN'),
('Albert Einstein but if he had a huge muscles and a rhinoceros cock.', 'GREEN'),
('Assassinating the president.', 'GREEN'),
('A woman&apos;s right to choose.', 'GREEN'),
('Eternal screaming madness.', 'GREEN'),
('Late-stage dementia.', 'GREEN'),
('Consensual, nonreproductive incest.', 'GREEN'),
('Swearing praise upon the Sultan&apos;s hideous daughters.', 'GREEN'),
('A cheerfulness that belies a deep-seated self-loathing.', 'GREEN'),
('An arrangement wherein I give a person money they have sex with me.', 'GREEN'),
('A genetic predisposition for alcoholism.', 'GREEN'),
('The wind.', 'GREEN'),
('Getting pegged.', 'GREEN'),
('Period poops.', 'GREEN'),
('The chicken from Popeyes. &reg;', 'GREEN'),
('A massive collection of child pornography.', 'GREEN'),
('A big, beautiful mouth packed to the brim with sparkling teeth.', 'GREEN'),
('Pooping in the potty.', 'GREEN'),
('Getting eaten out by a dog.', 'GREEN'),
('Munchin&apos; puss.', 'GREEN'),
('It being too late to stop having sex with a horse.', 'GREEN'),
('One of those &quot;blow jobs&quot; I&apos;ve been hearing so much about.', 'GREEN'),
('The lived experience of African Americans.', 'GREEN'),
('Prematurely ejaculating like a total loser.', 'GREEN'),
('Big, smart money boys tap-tapping on their keyboards.', 'GREEN'),
('Homework.', 'GREEN'),
('A finger up the butt.', 'GREEN'),
('Tiny, rancid girl farts.', 'GREEN'),
('The sweet, forbidden meat of the money.', 'GREEN'),
('Farting all over my face with your tight little asshole.', 'GREEN'),
('Doing a somersault and barfing.', 'GREEN'),
('The government.', 'GREEN'),
('How good lead paint taste.', 'GREEN'),
('Every man&apos;s ultimate fantasy: a perfectly cylindrical vagina.', 'GREEN'),
('Rubbing my bush all over your bald head.', 'GREEN'),
('Feeling the emotion of anger.', 'GREEN'),
('Gregor, my largest son.', 'GREEN'),
('A strong horse and enough rations for thirty days.', 'GREEN'),
('Getting aborted.', 'GREEN'),
('Systems and policies designed to preserve centuries-old power structures.', 'GREEN'),
('Overthrowing the democratically-elected government of Chile.', 'GREEN'),
('A weird guy who says weird stuff and weirds me out.', 'GREEN'),
('How strange it is to be anything at all.', 'GREEN'),
('Twenty cheerleaders laughing at your tiny penis.', 'GREEN'),
('Everything.', 'GREEN'),
('The flaming wreckage of the International Space Station.', 'GREEN'),
('A duffel bag full of lizards.', 'GREEN'),
('Beyonc&eacute;.', 'GREEN'),
('The fear and hatred in men&apos;s hearts.', 'GREEN'),
('One of them big-city Jew lawyers.', 'GREEN'),
('An empowered woman.', 'GREEN'),
('Tables.', 'GREEN'),
('The amount of baby carrots I can fit up my ass.', 'GREEN'),
('Farting a huge shit out of my pussy.', 'GREEN'),
('Being sexually attracted to children.', 'GREEN'),
('Participating.', 'GREEN'),
('Blossoming into a beautiful young woman.', 'GREEN'),
('Discovering that what I really want in life is to kill people and have sex with their corpses.', 'GREEN'),
('Breastfeeding in public like a radiant earth goddess.', 'GREEN'),
('ISIS.', 'GREEN'),
('All these people I&apos;ve killed.', 'GREEN'),
('The full force of the American military.', 'GREEN'),
('Eating ass.', 'GREEN'),
('Who really did 9/11.', 'GREEN'),
('Condoleezza Rice.', 'GREEN'),
('Content.', 'GREEN'),
('Creamy slices of real, California avocado.', 'GREEN'),
('How sad it will be when Morgan Freeman dies.', 'GREEN'),
('A black friend.', 'GREEN'),
('Whooping your ass at Mario Kart.', 'GREEN'),
('Sudden and unwanted slam poetry.', 'GREEN'),
('A cold and indifferent universe.', 'GREEN'),
('Pure Moods , Vol. 1.', '90s'),
('The best, deepest quotes from The Dark Night.', 'GREEN'),
('Salsa Night at Dave&apos;s Cantina.', 'GREEN'),
('Dominating a man by peeing on his eldest son.', 'GREEN'),
('Two shitty kids and a garbage husband.', 'GREEN'),
('The Rwandan Genocide.', 'GREEN'),
('The LGBT community.', 'GREEN'),
('Founding a major world religion.', 'GREEN'),
('Rolling so hard.', 'GREEN'),
('My huge penis and substantial fortune.', 'GREEN'),
('Forty-five minutes of finger blasting.', 'GREEN'),
('How great my ass looks in these jeans.', 'GREEN'),
('Pooping in a leotard and hoping no one notices.', 'GREEN'),
('Guns.', 'GREEN'),
('Getting this party started!', 'GREEN'),
('Twenty bucks.', 'GREEN'),
('Getting laid like all the time.', 'GREEN'),
('A big ol&apos; plate of fettuccine alfredo.', 'GREEN'),
('Showing all the boys my pussy.', 'GREEN'),
('Fucking me good and taking me to Red Lobster.&reg;', 'GREEN'),
('A terrified fat child who won&apos;t come out of the bushes.', 'GREEN'),
('Doritos and a Fruit Roll-Up.', 'GREEN'),
('Mommy and daddy fighting all the time.', 'GREEN'),
('Holding the proper political beliefs of my time to attract a mate.', 'GREEN'),
('Onions.', 'GREEN'),
('Self-identifying as a DJ.', 'GREEN'),
('Watching you die.', 'GREEN'),
('Some real spicy shrimps.', 'GREEN'),
('A burrito that&apos;s just sour cream.', 'GREEN'),
('The bond between a woman and her horse.', 'GREEN'),
('The secret to truly resilient hair.', 'GREEN'),
('Mental illness.', 'GREEN'),
('Gayle from HR.', 'GREEN'),
('Informing you that I am a registered sex offender.', 'GREEN'),
('A negative body image that is totally justified.', 'GREEN'),
('Political correctness.', 'GREEN'),
('The clown that followed me home from the grocery store.', 'GREEN'),
('That bitch, Stacy.', 'GREEN'),
('Ejaculating at the apex of a cartwheel.', 'GREEN'),
('Gazpacho.', 'GREEN'),
('Having sex with a man and then eating his head.', 'GREEN'),
('An older man.', 'GREEN'),
('An X-Man whose power is that he has sex with dogs and children.', 'GREEN'),
('Out-of-control teenage blowjob parties.', 'GREEN'),
('Tender chunks of all-white-meat chicken.', 'GREEN'),
('Crushing the patriarchy.', 'GREEN'),
('The full blown marginalization of ugly people.', 'GREEN'),
('Aborting the shit out of a fetus.', 'GREEN'),
('Film roles for actresses over 40.', 'GREEN'),
('Plowing that ass like a New England corn farmer.', 'GREEN'),
('Huge big balls full of jizz.', 'GREEN'),
('Some of that good dick.', 'GREEN'),
('Being turned into sausages.', 'GREEN'),
('Hating Jews.', 'GREEN'),
('Crazy anal orgasms.', 'GREEN'),
('Regurgitating a half-digested sparrow.', 'GREEN'),
('The ol&apos; penis-in-the-popcorn surprise.', 'GREEN'),
('A tiny fireman who puts out tiny fires.', 'GREEN'),
('Dis bitch.', 'GREEN'),
('Trees.', 'GREEN'),
('Three hours of nonstop penetration.', 'GREEN'),
('Slamming a dunk.', 'GREEN'),
('Starting a shitty podcast.', 'GREEN'),
('Gary.', 'GREEN'),
('Feminism.', 'GREEN'),
('Our baby.', 'GREEN'),
('Falling into a pit of waffles.', 'GREEN'),
('A woman&apos;s perspective.', 'GREEN'),
('Chipotle.', 'GREEN'),
('Scissoring, if that&apos;s a thing.', 'GREEN'),
('Watching a hot person eat.', 'GREEN'),
('Defeating a gorilla in single combat.', 'GREEN'),
('Bad emotions I don&apos;t want.', 'GREEN'),
('A creepy child singing a nursery rhyme.', 'GREEN'),
('Comprehensive immigration reform.', 'GREEN'),
('Denying the Holocaust.', 'GREEN'),
('Two beautiful pig sisters.', 'GREEN'),
('Catching a live salmon in your mouth.', 'GREEN'),
('Daddy going away forever.', 'GREEN'),
('A medium horchata.', 'GREEN'),
('Libertarians.', 'GREEN'),
('Picking up a glass of water and taking a sip and being the president.', 'GREEN'),
('Waking up inside of a tornado.', 'GREEN'),
('Making out and stuff.', 'GREEN'),
('A slowly encroaching circle of wolves.', 'GREEN'),
('Opening your mouth to talk and a big penis fops out.', 'GREEN'),
('Eating too many Cinnabons and then vomiting and then eating the vomit.', 'GREEN'),
('Seizing control of the means of production.', 'GREEN'),
('Misogyny.', 'GREEN'),
('Thinking about what eating even is.', 'GREEN'),
('Dropping dead in a Sbarro&apos;s bathroom and not being found for 72 hours.', 'GREEN'),
('Sucking each other&apos;s penises for hours on end.', 'GREEN'),
('Awesome pictures of planets and stuff.', 'GREEN'),
('Microaggressions.', 'GREEN'),
('Pretending to be one of the guys but actually being the spider god.', 'GREEN'),
('Fucking my therapist.', 'GREEN'),
('Having sex with a beautiful person.', 'GREEN'),
('Moon people.', 'GREEN'),
('Jason, the teen mayor.', 'GREEN'),
('Quinoa.', 'GREEN'),
('China.', 'GREEN'),
('Menopause.', 'GREEN'),
('My dog dying.', 'GREEN'),
('A gun that shoots cobras.', 'GREEN'),
('Reaching an age where barbecue chips are better than sex.', 'GREEN'),
('Going around pulling people&apos;s tampons out.', 'GREEN'),
('Playing my asshole like a trumpet.', 'GREEN'),
('Getting blasted in the face by a t-shirt cannon.', 'GREEN'),
('Getting naked too soon.', 'GREEN'),
('Pamela Anderson&apos;s boobs running in slow motion.', '90s'),
('A bus that will explode if it goes under 50 miles per hour.', '90s'),
('Jerking off to a 10-second RealMedia clip.', '90s'),
('Pizza in the morning, pizza in the evening, pizza at supper time.', '90s'),
('Stabbing the shit out of a Capri Sun.', '90s'),
('Angels interfering in an otherwise fair baseball game.', '90s'),
('Sucking the President&apos;s dick.', '90s'),
('Sunny D! Alright!', '90s'),
('The Great Cornholio.', '90s'),
('Painting with all the colors of the wind.', '90s'),
('Cool 90s up-in-the-front hair.', '90s'),
('The Y2K bug.', '90s'),
('A mulatto, an albino, a mosquito, and my libido.', '90s'),
('Liking big butts and not being able to lie about it.', '90s'),
('Deregulating the mortgage market.', '90s'),
('Kurt Cobain&apos;s death.', '90s'),
('A threesome with 1996 Denise Richards and 1999 Denise Richards.', '90s'),
('Freeing Willy.', '90s'),
('Several Michael Keatons.', '90s'),
('Patti Mayonnaise.', '90s'),
('Wearing Nicolas Cage&apos;s face.', '90s'),
('Log.&trade;', '90s'),
('Santa&apos;s heavy sack.', '❄2012'),
('Donald Trump holding his nose while he eats pussy.', 'V4HIL'),
('Black lives mattering.', 'V4HIL'),
('Kicking the middle class in the balls with a regressive tax code.', 'V4HIL'),
('Slapping Ted Cruz over and over.', 'V4HIL'),
('Eating the president&apos;s pussy.', 'V4HIL'),
('Keeping the government out of my vagina.', 'V4HIL');

INSERT INTO `answers` (`answer`, `deck`)
VALUES 
('The fact that Hillary Clinton is a woman.', 'V4HIL'),
('Increasing economic inequality and political polarization.', 'V4HIL'),
('The Bernie Sanders revolution.', 'V4HIL'),
('A beautiful, ever-expanding circle of inclusivity that will never include Republicans.', 'V4HIL'),
('Letting Bernie Sanders rest his world-weary head on your lap.', 'V4HIL'),
('The systemic disenfranchisement of black voters.', 'V4HIL'),
('Eating an entire snowman.', '❄2013'),
('A Christmas stocking full of coleslaw.', '❄2013'),
('Elf cum.', '❄2013'),
('Giving money and personal information to strangers on the Internet.', '❄2013'),
('The royal afterbirth.', '❄2013'),
('A magical tablet containing a world of unlimited pornography.', '❄2013'),
('A toxic family environment.', '❄2013'),
('Breeding elves for their priceless semen.', '❄2013'),
('Clearing a bloody path through Walmart with a scimitar.', '❄2013'),
('Slicing a ham in icy silence.', '❄2013'),
('A simultaneous nightmare and wet dream starring Sigourney Weaver.', '❄2013'),
('A visually arresting turtleneck.', '❄2013'),
('The shittier, Jewish version of Christmas.', '❄2013'),
('Gift-wrapping a live hamster.', '❄2013'),
('Moses gargling Jesus&apos;s balls while Shiva and the Buddha penetrate his divine hand holes.', '❄2013'),
('Socks.', '❄2013'),
('These low, low prices!', '❄2013'),
('Finding out that Santa isn&apos;t real.', '❄2013'),
('The tiny, calloused hands of the Chinese children that made this card.', '❄2013'),
('The Star Wars Holiday Special.', '❄2013'),
('Rudolph&apos;s bright red balls.', '❄2013'),
('Jizzing into Santa&apos;s beard.', '❄2013'),
('Being blind and deaf and having no limbs.', '❄2013'),
('My hot cousin.', '❄2013'),
('Mall Santa.', '❄2013'),
('The Hawaiian goddess Kapo and her flying detachable vagina.', '❄2013'),
('Taking down Santa with a surface-to-air missile.', '❄2013'),
('Pretending to be happy.', '❄2013'),
('Fucking up &quot;Silent Night&quot; in front of 300 parents.', '❄2013'),
('Krampus, the Austrian Christmas monster.', '❄2013'),
('Several intertwining love stories featuring Hugh Grant.', '❄2013'),
('Space Jam on VHS.', '❄2013'),
('Swapping bodies with mom for a day.', '❄2013'),
('Another shitty year.', '❄2013'),
('Immaculate conception.', '❄2013'),
('People with cake in their mouths talking about how good cake is.', '❄2013'),
('Piece of shit Christmas cards with no money in them.', '❄2013'),
('Congress&apos;s flaccid penises withering away beneath their suit pants.', '❄2013'),
('Having a strong opinion about Obamacare.', '❄2013'),
('Whatever Kwanzaa is supposed to be about.', '❄2013'),
('A Hungry-Man&trade; Frozen Christmas Dinner for One.', '❄2013'),
('Making up for 10 years of shitty parenting with a PlayStation.', '❄2013'),
('The Grinch&apos;s musty, cum-stained pelt.', '❄2013'),
('Actually voting for Donald Trump to be President of the actual United States.', 'V4 45'),
('Growing up and becoming a Republican.', 'V4 45'),
('A liberal bias.', 'V4 45'),
('Full-on socialism.', 'V4 45'),
('Hating Hillary Clinton.', 'V4 45'),
('Jeb!', 'V4 45'),
('Conservative talking points.', 'V4 45'),
('Courageously going ahead with that racist comment.', 'V4 45'),
('The good, hardworking people of Dubuque, Iowa.', 'V4 45'),
('Dispelling with this fiction that Barack Obama doesn&apos;t know what he&apos;s doing.', 'V4 45'),
('Shouting the loudest.', 'V4 45'),
('Sound fiscal policy.', 'V4 45'),
('Boxing up my feelings.', 'BOX'),
('An alternate universe in which boxes store things inside of people.', 'BOX'),
('Being a motherfucking box.', 'BOX'),
('The Boxcar Children.', 'BOX'),
('A box that is conscious and wishes it weren&apos;t a box.', 'BOX'),
('A box within a box.', 'BOX'),
('A man-shaped box.', 'BOX'),
('A world without boxes.', 'BOX'),
('A box of biscuits, a box of mixed biscuits, and a biscuit mixer.', 'BOX'),
('Former President George W. Box.', 'BOX'),
('A box without hinges, key, or lid, yet golden treasure inside is hid.', 'BOX'),
('A box-shaped man.', 'BOX'),
('The J15 Patriot Assault Box.', 'BOX'),
('Temporary invincibility.', '13PAX'),
('A falcon with a box on its head.', 'BOX'),
('Two midgets shitting into a box.', 'BOX'),
('An outbreak of smallbox.', 'BOX'),
('Something that looks like a box but turns out to be a crate.', 'BOX'),
('Pandora&apos;s vagina.', 'BOX'),
('A boxing match with a giant box.', 'BOX'),
('A box.', 'BOX'),
('Eight beautiful men jerking each other off in front of a fountain.', 'HIDDN'),
('Ruth Bader Ginsberg brutally gaveling your penis.', 'HIDDN'),
('A blind, quadriplegic AIDS survivor with face cancer and diarrhea.', 'HIDDN'),
('Free ice cream forever, or getting fingered by Chris Hemsworth for five minutes.', 'HIDDN'),
('Digging up Heath Ledger&apos;s corpse to reenact the prom scene from Ten Things I Hate About You.', 'HIDDN'),
('Throwing your hands in the air and waving them despite caring deeply.', 'HIDDN'),
('Chugging a gallon of milk and then vomiting a gallon of milk.', 'HIDDN'),
('How wonderful it is when my master throws the ball and I go and get it for him.', 'HIDDN'),
('Giving ISIS whatever they want so they leave us alone.', 'HIDDN'),
('Throwing a baby dolphin back into the ocean with a perfect spiral.', 'HIDDN'),
('Sitting in a jar of vinegar all night because I am pickle.', 'HIDDN'),
('Hickory-fucked pork ribs smothered in hot garbage.', 'HIDDN'),
('A homoerotic subplot.', 'HCARD'),
('The sensitive European photographer who&apos;s fucking my wife.', 'HCARD'),
('An origami swan that&apos;s some kind of symbol?', 'HCARD'),
('Carbon monoxide poisoning.', 'HCARD'),
('A childless marriage.', 'HCARD'),
('Ribs so good they transcend race and class.', 'HCARD'),
('25 shitty jokes about House of Cards.', 'HCARD'),
('Making it look like a suicide.', 'HCARD'),
('Forcing a handjob on a dying man.', 'HCARD'),
('Getting eaten out while on the phone with Dad.', 'HCARD'),
('My constituents.', 'HCARD'),
('Strangling a dog to make a point to the audience.', 'HCARD'),
('Discharging a firearm in a residential area.', 'HCARD'),
('Performative wokeness.', 'COLEG'),
('The sound of my roommate masturbating.', 'COLEG'),
('Rocking a 1.5 GPA.', 'COLEG'),
('Pretending to have done the reading.', 'COLEG'),
('Throw up.', 'COLEG'),
('Uggs, leggings, and a North Face.', 'COLEG'),
('Valuable leadership experience.', 'COLEG'),
('Whichever one of you took a shit in the shower.', 'COLEG'),
('Fucking the beat boxer from the a cappella group.', 'COLEG'),
('Five morons signing a lease together.', 'COLEG'),
('Googling how to eat pussy.', 'COLEG'),
('Sucking a flaccid penis for 20 minutes.', 'COLEG'),
('My high school boyfriend.', 'COLEG'),
('A bachelor&apos;s degree in communications.', 'COLEG'),
('Calling mom because it&apos;s just really hard and I miss her and I don&apos;t know anyone here.', 'COLEG'),
('Wandering the streets in search of a party.', 'COLEG'),
('Underage drinking.', 'COLEG'),
('Young Republicans.', 'COLEG'),
('A Yale man.', 'COLEG'),
('An emergency all-floor meeting of inclusion.', 'COLEG'),
('Going to college and becoming a new person, who has sex.', 'COLEG'),
('How many Asians there are.', 'COLEG'),
('A girl who is so interesting that she has blue hair.', 'COLEG'),
('Falling in love with poetry.', 'COLEG'),
('Being replaced by a robot.', '❄2014'),
('The events depicted in James Cameron&apos;s Avatar.', '❄2014'),
('Blockbuster late fees up the wazoo.', '❄2014'),
('All the poop inside of my body.', '❄2014'),
('A protracted siege.', '❄2014'),
('The diminishing purity of the white race.', '❄2014'),
('Trying to feel something, anything.', '❄2014'),
('A cloud of ash that darkens the Earth for a thousand years.', '❄2014'),
('A vague fear of something called ISIS.', '❄2014'),
('200 years of slavery.', '❄2014'),
('The transience of all things.', '❄2014'),
('Ebola.', '❄2014'),
('Small-town cops with M4 assault rifles.', '❄2014'),
('Rising sea levels consistent with scientific predictions.', '❄2014'),
('What remains of my penis.', '❄2014'),
('Harnessing the miraculous power of the atom to slaughter 200,000 Japanese people.', '❄2014'),
('This groovy new thing called LSD.', '❄2014'),
('Building a ladder of hot dogs to the moon.', '❄2014'),
('Rock music and premarital sex.', '❄2014'),
('The Great Lizard Uprising of 2352.', '❄2014'),
('The dying breath of the last human.', '❄2014'),
('Reading an entire book.', '❄2014'),
('The 9,000 children who starved to death today.', '❄2014'),
('The Bowflex Revolution.', '❄2014'),
('Falling in actual love with a video game character.', 'MSFX'),
('My complicated backstory that you will soon learn about.', 'MSFX'),
('The Genophage.', 'MSFX'),
('Totally fuckable aliens.', 'MSFX'),
('Running a few errands before saving the galaxy.', 'MSFX'),
('Bone-shattering sex with a metal woman.', 'MSFX'),
('Space racism.', 'MSFX'),
('An emergency induction port.', 'MSFX'),
('An armored Krogan war-clitoris.', 'MSFX'),
('An extremely long elevator ride.', 'MSFX'),
('Forgetting to convert pound-seconds into newton-seconds.', 'NASA'),
('Uranus.', 'NASA'),
('A zero-g cumshot.', 'NASA'),
('Seven minutes of terror.', 'NASA'),
('A slow, shitty car that drives around Mars for no reason.', 'NASA'),
('Discovering some bullshit microscopic life instead of anything cool.', 'NASA'),
('Achieving escape velocity.', 'NASA'),
('Dreaming of going to space, but being hopelessly fat.', 'NASA'),
('Dinosaurs who wear armor and you ride them and they kick ass.', 'FNTSY'),
('Full HD.', '13PAX'),
('Accidentally conjuring a legless horse that can&apos;t stop ejaculating.', 'FNTSY'),
('Shitting in a wizard&apos;s spell book and jizzing in his hat.', 'FNTSY'),
('A Hitachi Magic Wand.', 'FNTSY'),
('Reading The Hobbit under the covers while mom and dad scream at each other downstairs.', 'FNTSY'),
('How hot Orlando Bloom was in Lord of the Rings.', 'FNTSY'),
('A mysterious, floating orb.', 'FNTSY'),
('Shooting a wizard with a gun.', 'FNTSY'),
('Hodor.', 'FNTSY'),
('Make-believe stories for autistic white men.', 'FNTSY'),
('A magical kingdom with dragons and elves and no black people.', 'FNTSY'),
('The card Neil Gaiman wrote: &quot;Three elves at a time.&quot;', 'FNTSY'),
('Gender equality.', 'FNTSY'),
('Going on an epic adventure and learning a valuable lesson about friendship.', 'FNTSY'),
('True love&apos;s kiss.', 'FNTSY'),
('Eternal darkness.', 'FNTSY'),
('The all-seeing Eye of Sauron.', 'FNTSY'),
('Bathing naked in a moonlit grove.', 'FNTSY'),
('Handcuffing a wizard to a radiator and dousing him with kerosene.', 'FNTSY'),
('Kneeing a wizard in the balls.', 'FNTSY'),
('A ghoul.', 'FNTSY'),
('A weed elemental who gets everyone high.', 'FNTSY'),
('A gay sorcerer who turns everyone gay.', 'FNTSY'),
('A CGI dragon.', 'FNTSY'),
('Freaky, pan-dimensional sex with a demigod.', 'FNTSY'),
('A dwarf who won&apos;t leave you alone until you compare penis sizes.', 'FNTSY'),
('How many drinks Aunt Deborah has had.', '❄'),
('A snowman that contains the soul of my dead father.', '❄'),
('A choir of angels descending from the sky and jizzing all over dad&apos;s sweater.', '❄'),
('Probably Grandma&apos;s last Christmas, kids.', '❄'),
('A frozen homeless man shattering on your doorstep.', '❄'),
('Snow falling gently on the frozen body of an orphan boy.', '❄'),
('My uncle who voted for Trump.', '❄'),
('How great of a blowjob Jesus could give.', '❄'),
('Starting to see where ISIS is coming from.', '❄'),
('Fucking up Silent Night in front of 300 parents.', '❄'),
('How cool it is that I love Jesus and he loves me back.', '❄'),
('An immediately regrettable $9 hot dog from the Boston Convention Center.', 'PE13A'),
('Paying the iron price.', 'PE13A'),
('Casting Magic Missile at a bully.', 'PE13A'),
('Rotating shapes in mid-air so that they fit into other shapes when they fall.', 'PE13A'),
('Firefly: Season 2.', 'PE13A'),
('Jiggle physics.', 'PE13A'),
('Getting bitch slapped by Dhalsim.', 'PE13A'),
('Running out of stamina.', 'PE13A'),
('Sharpening a foam broadsword on a foam whetstone.', 'PE13B'),
('The depression that ensues after catching &apos;em all.', 'PE13B'),
('Loading from a previous save.', 'PE13B'),
('The rocket launcher.', 'PE13B'),
('Getting inside the Horadric Cube with a hot babe and pressing the transmute button.', 'PE13B'),
('Spending the year&apos;s insulin budget on Warhammer 40k figurines.', 'PE13B'),
('Punching a tree to gather wood.', 'PE13B'),
('Violating the First Law of Robotics.', 'PE13B'),
('Charging up all the way.', 'PE13C'),
('Vespene gas.', 'PE13C'),
('Wil Wheaton crashing an actual spaceship.', 'PE13C'),
('The Klobb.', 'PE13C'),
('Achieving 500 actions per minute.', 'PE13C'),
('Smashing all the pottery in a Pottery Barn in search of rupees.', 'PE13C'),
('Forgetting to eat, and consequently dying.', 'PE13C'),
('Judging elves by the color of their skin and not by the content of their character.', 'PE13C'),
('Kevin Bacon Bits.', 'FOOD'),
('Being emotionally and physically dominated by Gordon Ramsay.', 'FOOD'),
('A belly full of hard-boiled eggs.', 'FOOD'),
('Kale farts.', 'FOOD'),
('Clamping down on a gazelle&apos;s jugular and tasting its warm life waters.', 'FOOD'),
('A table for one at The Cheesecake Factory.', 'FOOD'),
('The hot dog I put in my vagina ten days ago.', 'FOOD'),
('The Dial-A-Slice Apple Divider from Williams-Sonoma.', 'FOOD'),
('Oreos for dinner.', 'FOOD'),
('A joyless vegan patty.', 'FOOD'),
('Soup that&apos;s better than pussy.', 'FOOD'),
('The Hellman&apos;s Mayonnaise Corporation.', 'FOOD'),
('Going vegetarian and feeling so great all the time.', 'FOOD'),
('Not knowing what to believe anymore about butter.', 'FOOD'),
('A sobering quantity of chili cheese fries.', 'FOOD'),
('Licking the cake batter off of grandma&apos;s fingers.', 'FOOD'),
('Real cheese flavor.', 'FOOD'),
('Swishing the wine around and sniffing it like a big fancy man.', 'FOOD'),
('Sucking down thousands of pounds of krill every day.', 'FOOD'),
('The inaudible screams of carrots.', 'FOOD'),
('Committing suicide at the Old Country Buffet.', 'FOOD'),
('What to do with all of this chocolate on my penis.', 'FOOD'),
('Father&apos;s forbidden chocolates.', 'FOOD'),
('Jizz Twinkies.', 'FOOD'),
('Tapping Serra Angel.', '13PAX'),
('The gravity gun.', '13PAX'),
('Never watching, discussing, or thinking about My Little Pony.', '13PAX'),
('Reading the comments.', '13PAX'),
('The Sarlacc.', '13PAX'),
('Unlocking a new sex position.', '13PAX'),
('Being an attractive elf trapped in an unattractive human&apos;s body.', '13PAX'),
('Bowser&apos;s aching heart.', '13PAX'),
('Charles Barkley Shut Up and Jam!', '13PAX'),
('70,000 games sweating and farting inside an airtight steel dome.', '13PAX'),
('The collective wail of every Magic player suddenly realizing that they&apos;ve spent hundreds of dollars on pieces of cardboard.', '13PAX'),
('Legendary Creature Robert Khoo.', '13PAX'),
('Allowing nacho cheese to curdle in your beard while you creep in League of Legends.', '13PAX'),
('Winning the approval of Cooking Mama that you never got from actual mama.', '13PAX'),
('The boner hatch in the Iron Man suit.', '13PAX'),
('Buying virtual clothes for a Sim family instead of real clothes for a real family.', '13PAX'),
('An angry stone head that stomps on the floor every three seconds.', '13PAX'),
('Offering sexual favors for an ore and a sheep.', '13PAX'),
('Turn-of-the-century-sky racists.', '13PAX'),
('Getting into a situation with an owlbear.', '13PAX'),
('Grand Theft Auto: Fort Lauderdale.', '13PAX'),
('Achieving the manual dexterity and tactical brilliance of a 12-year-old Korean boy.', '13PAX'),
('The decade of legal inquests following a single hour of Grand Theft Auto.', '13PAX'),
('SNES cartridge cleaning fluid.', '13PAX'),
('Eating a pizza that&apos;s lying in the street to gain health.', '13PAX'),
('Mario Kart rage.', '13PAX'),
('A homemade, cum-stained Star Trek uniform.', '13PAX'),
('Google Glass + e-cigarette: Ultimate Combo!', '13PAX'),
('Yoshi&apos;s huge egg-laying cloaca.', '13PAX'),
('A fully-dressed female videogame character.', '13PAX'),
('Nude-modding Super Mario World.', '13PAX'),
('A madman who lives in a policebox and kidnaps women.', '13PAX'),
('Filling every pouch of a UtiliKilt&trade; with pizza.', '13PAX'),
('The Cock Ring of Alacrity.', '13PAX'),
('Rolling a D20 to save a failing marriage.', '13PAX'),
('Getting bitten by a radioactive spider and then battling leukemia for 30 years.', 'GEEK'),
('Separate drinking fountains for dark elves.', 'GEEK'),
('Stuffing my balls into a Sega Genesis and pressing the power button.', 'GEEK'),
('Ser Jorah Mormont&apos;s cerulean-blue balls.', 'GEEK'),
('A grumpy old Harrison Ford who&apos;d rather be doing anything else.', 'GEEK'),
('Taking 2d6 emotional damage.', 'GEEK'),
('KHAAAAAAAAAN!', 'GEEK'),
('Endless ninjas.', 'GEEK'),
('Demons and shit.', '14PAX'),
('Collecting all seven power crystals.', '14PAX'),
('Xena, Warrior Princess.', '14PAX'),
('The old gods.', '14PAX'),
('The Star Wars Universe.', '14PAX'),
('The imagination of Peter Jackson.', '14PAX'),
('Lagging out.', '14PAX'),
('All of the good times and premium gaming entertainment available to you in the Kickstarter room.', '14PAX'),
('Attacking from Kamchatka.', '14PAX'),
('The pure, Zen-like state that exists between micro and macro.', '14PAX'),
('Mistakenly hitting on a League of Legends statue.', '14PAX'),
('A giant mechanical bird with a tragic backstory.', '14PAX'),
('Whatever Final Fantasy bullshit happened this year.', '14PAX'),
('Futuristic death sports.', '14PAX'),
('Resurrecting an army of six million Jews and conquering Germany.', 'JEW'),
('The part of Anne Frank&apos;s diary where she talks about her vagina.', 'JEW'),
('Sacrificing Isaac to the Lord.', 'JEW'),
('The ethical implications of enjoying a Woody Allen film in light of the allegations against him.', 'JEW'),
('Chopping off a bit of the penis.', 'JEW'),
('Some kind of concentrated encampment for people.', 'JEW'),
('Pork products.', 'JEW'),
('Wandering the desert for 40 years.', 'JEW'),
('What it means to be a Jewish woman in contemporary society.', 'JEW'),
('Suddenly remembering that the Holocaust happened.', 'JEW'),
('Thy neighbor&apos;s wife.', 'JEW'),
('Holding up the line at Walgreens by trying to use an expired coupon.', 'JEW'),
('Demolishing that ass like a Palestinian village.', 'JEW'),
('Being chosen by God to win a free iPod Nano.', 'JEW'),
('A little bit of schmutz right there.', 'JEW'),
('Torturing Jews until they say they&apos;re not Jews anymore.', 'JEW'),
('A lifetime of internalized guilt.', 'JEW'),
('A three-foot-tall corned beef sandwich.', 'JEW'),
('Usury.', 'JEW'),
('Hiding from the Nazis.', 'JEW'),
('Bags of money.', 'JEW'),
('The blood of Christian babies.', 'JEW'),
('A headache that&apos;s definitely cancer.', 'JEW'),
('A big brain full of facts and sadness.', 'JEW'),
('Whoopi Goldberg.', 'JEW'),
('Whipping lower-class white men into a xenophobic frenzy.', 'PST45'),
('Extra rations for my little girl.', 'PST45'),
('Roaming through a wasteland of windblown trash and deserted highways.', 'PST45'),
('Drinking urine to survive.', 'PST45'),
('A legitimate reason to commit suicide.', 'PST45'),
('Burying my only son.', 'PST45'),
('Desperately hurling insults at Donald Trump as he absorbs them into his rapidly expanding body.', 'PST45'),
('Trying to remember what music was.', 'PST45'),
('Casual dismissiveness.', 'PST45'),
('Finding out that democracy might not be such a great idea.', 'PST45'),
('A father and son fighting each other over the last scrap of bread.', 'PST45'),
('Mild amusement.', 'PST45'),
('A back-alley abortion from a Mexican cyborg doctor.', 'PST45'),
('Rage.', 'PST45'),
('World Wards 3 through 5.', 'PST45'),
('President Donald Trump.', 'PST45'),
('Making Islam illegal.', 'PST45'),
('Trying to wake up from this nightmare.', 'PST45'),
('The purging of the disloyal.', 'PST45'),
('Nuclear winter.', 'PST45'),
('Bringing millions of dangerous, low-paying manufacturing jobs back to America.', 'PST45'),
('A gnawing sense of dread.', 'PST45'),
('Period globs.', '.'),
('Always&reg; Infinity Extra Heavy Overnight Pads with Wings.', '.'),
('Wringing out a sopping wet maxi pad in Donald Trump&apos;s mouth.', '.'),
('Playing with my pussy while I watch TV.', '.'),
('An emotionally draining friendship.', '.'),
('Post-partum depression.', '.'),
('Full bush.', '.'),
('Drinking Beyonce&apos;s DivaCup and becoming immortal.', '.'),
('Feeling lots of feelings.', '.'),
('Carrying a fetus to term.', '.'),
('Eating three sleeves of Chips Ahoy!', '.'),
('Destroying a pair of underwear.', '.'),
('Masturbating with a Sonicare.', '.'),
('How bloody that dick&apos;s about to be.', '.'),
('The vagina hole.', '.'),
('Dancing carefree in white linen pants.', '.'),
('Pussy lips of all shapes and sizes.', '.'),
('Using a Smucker&apos;s Uncrustable&trade; as a maxi pad.', '.'),
('Pulling out a never-ending tampon.', '.'),
('Catching a whiff of my vag.', '.'),
('A diverse group of female friends casually discussing the side effects of birth control.', '.'),
('A woman president.', '.'),
('Driving my daughter to her abortion.', '.'),
('Feeling bloaty and crampy.', '.'),
('Caribbean Jesus.', 'RJECT'),
('Corn.', 'RJECT'),
('Super yoga.', 'RJECT'),
('A sexy naked interactive theater thing.', 'RJECT'),
('Actually believing that the Bible happened.', 'RJECT'),
('A giant squid in a wedding gown.', 'RJECT'),
('A heart that is two sizes too small and that therefore cannot pump an adequate amount of blood.', 'RJECT'),
('Ejaculating a pound of tinsel.', 'RJECT'),
('Crawling into a vagina.', 'RJECT'),
('Faking a jellyfish sting so someone will pee on you.', 'RJECT'),
('My dick in your mouth.', 'RJECT'),
('Asshole pomegranates that are hard to eat.', 'RJECT'),
('The John D. and Catherine T. MacArthur Foundation.', 'RJECT'),
('Dividing by zero.', 'RJECT'),
('Becoming so rich that you shed your body and turn into vapor.', 'RJECT'),
('Playing an ocarina to summon Ultra-Congress from the sea.', 'RJECT'),
('Feeding a man a pie made of his own children.', 'RTAIL'),
('Ironically buying a trucker hat and then ironically being a trucker for 38 years.', 'RTAIL'),
('A teenage boy gunning for a handjob.', 'RTAIL'),
('Going too far with science and bad things happening.', 'SCIFI'),
('Frantically writing equations on a chalkboard.', 'SCIFI'),
('An alternate history where Hitler was gay but he still killed all those people.', 'SCIFI'),
('A hazmat suit full of farts.', 'SCIFI'),
('That girl from the Hungry Games.', 'SCIFI'),
('Funkified aliens from the planet Groovius.', 'SCIFI'),
('The ending of Lost.', 'SCIFI'),
('Vulcan sex-madness.', 'SCIFI'),
('Three boobs.', 'SCIFI'),
('A misty room full of glistening egg sacs.', 'SCIFI'),
('Cheerful blowjob robots.', 'SCIFI'),
('How great of a movie Men in Black was.', 'SCIFI'),
('A planet-devouring space worm named Rachel.', 'SCIFI'),
('Beep beep boop beep boop.', 'SCIFI'),
('Nine seasons of sexual tension with David Duchovny.', 'SCIFI'),
('Darmok and Jalad at Tanagra.', 'SCIFI'),
('A protagonist with no qualities.', 'SCIFI'),
('The dystopia we&apos;re living in right now.', 'SCIFI'),
('Cosmic bowling.', 'SCIFI'),
('Masturbating Yoda&apos;s leathery turtle-penis.', 'SCIFI'),
('Laying thousands of eggs in a man&apos;s colon.', 'SCIFI'),
('Trimming poop out of Chewbacca&apos;s butt hair.', 'SCIFI'),
('Sandwich.', 'RJCT2'),
('At least three ducks.', 'RJCT2'),
('Mushy tushy.', 'RJCT2'),
('Saving the Rainforest Cafe.', 'RJCT2'),
('Becoming engorged with social justice jelly and secreting a thinkpiece.', 'RJCT2'),
('That one leftover screw.', 'RJCT2'),
('Greg Kinnear&apos;s terrible lightning breath.', 'RJCT2'),
('Sir Thomas More&apos;s Fruitopia.&trade;', 'RJCT2'),
('Mr. and Mrs. Tambourine Man&apos;s jingle-jangle morning sex.', 'RJCT2'),
('The spooky skeleton under my skin.', 'RJCT2'),
('A double murder suicide barbeque.', 'RJCT2'),
('Sweating it out on the streets of a runaway American Dream.', 'RJCT2'),
('Disco Mussolini.', 'RJCT2'),
('That thing politicians do with their thumbs when they talk.', 'RJCT2'),
('These dolphins.', 'RJCT2'),
('A dick so big and so black that not even light can escape its pull.', 'RJCT2'),
('Being the absolute worst.', 'RJCT2'),
('A primordial soup and salad bar.', 'RJCT2'),
('Three hairs from the silver-golden head of Galadriel.', 'RJCT2'),
('A stack of bunnies in a trenchcoat.', 'RJCT2'),
('Mitt Romney&apos;s eight sons Kip, Sam, Trot, Fergis, Toolshed, Grisham, Hawkeye, and Thorp.', 'RJCT2'),
('Ringo Starr &amp; His All-Starr Band.', 'RJCT2'),
('The token lesbian.', 'RJCT2'),
('Water so cold it turned into a rock.', 'RJCT2'),
('Being knowledgeable in a narrow domain that nobody understands or cares about.', 'SCI'),
('A supermassive black hole.', 'SCI'),
('A 0.7 waist-to-hip ratio.', 'SCI'),
('The quiet majesty of the sea turtle.', 'SCI'),
('Photosynthesis.', 'SCI'),
('Getting really worried about global warming for a few seconds.', 'SCI'),
('Infinity.', 'SCI'),
('Reconciling quantum theory with general relativity.', 'SCI'),
('Driving into a tornado to learn about tornadoes.', 'SCI'),
('Explosive decompression.', 'SCI'),
('Oxytocin release via manual stimulation of the nipples.', 'SCI'),
('Developing secondary sex characteristics.', 'SCI'),
('David Attenborough watching us mate.', 'SCI'),
('Achieving reproductive success.', 'SCI'),
('Electroejaculating a capuchin monkey.', 'SCI'),
('Insufficient serotonin.', 'SCI'),
('Slowly evaporating.', 'SCI'),
('Failing the Turing test.', 'SCI'),
('Evolving a labyrinthe vagina.', 'SCI'),
('Fun and interesting facts about rocks.', 'SCI'),
('The Sun engulfing the Earth.', 'SCI'),
('3.7 billion years of evolution.', 'SCI'),
('A Pringles&reg; can full of screams.', 'RTPRD'),
('A framed photocopy of an oil painting of Paris, France.', 'RTPRD'),
('Buying the right toothbrush cup for my lifestyle.', 'RTPRD'),
('Shiny gadgets for sadness distraction.', 'RTPRD'),
('Saving 20% or more on khakis.', 'RTPRD'),
('How fun it is to eat Pringles&reg;.', 'RTPRD'),
('Refusing to go up a size.', 'RTPRD'),
('An exclusive partnership with Taylor Swift.', 'RTPRD'),
('An 800-foot-long pool noodle.', 'RTPRD'),
('Confusing possessions with accomplishments.', 'RTPRD'),
('Blood Pringles&reg;.', 'RTPRD'),
('Crunchy snacks for my big flappy mouth.', 'RTPRD'),
('A Pringle&reg;.', 'RTPRD'),
('Subsisting on tiny pizzas.', 'RTPRD'),
('Extracting the maximum amount of money from naive consumers.', 'RTPRD'),
('The obscene amount of money Cards Against Humanity is making by selling this game at Target.&reg;', 'RTPRD'),
('Gender-neutral toys that make children feel no emotions whatsoever.', 'RTPRD'),
('Getting eaten out in the family fitting room.', 'RTPRD'),
('Buying and returning clothes just to have someone to talk to.', 'RTPRD'),
('A marriage-destroying game of The Resistance .', 'TBLTP'),
('SIX GOD DAMN HOURS OF FUCKING DIPLOMACY.', 'TBLTP'),
('Condensing centuries of economic exploitation into 90 minutes of gaming fun.', 'TBLTP');

INSERT INTO `answers` (`answer`, `deck`)
VALUES 
('Spending 8 years in the Himalayas becoming a master of dice-rolling and resource allocation.', 'TBLTP'),
('A disappointing season of Tabletop that&apos;s just about tables.', 'TBLTP'),
('A zombie with a tragic backstory.', 'TBLTP'),
('A Wesley Crusher blow-up doll.', 'TBLTP'),
('The porn set that Tabletop is filmed on.', 'TBLTP'),
('An owlbear.', 'TBLTP'),
('The pooping position.', 'TBLTP'),
('A German-style board game where you invade Poland.', 'TBLTP'),
('Victory points.', 'TBLTP'),
('How bright the sun is.', 'WEED'),
('Grinning like an idiot.', 'WEED'),
('Smoking a blunt butt-ass naked.', 'WEED'),
('Forgetting to breathe and then dying.', 'WEED'),
('Dank ass cancer weed.', 'WEED'),
('Snoop Dogg.', 'WEED'),
('A whole cheese pizza just for me.', 'WEED'),
('Dicking around on the guitar for an hour.', 'WEED'),
('Cheesy crunchies.', 'WEED'),
('Whatever the fuck I was just talking about.', 'WEED'),
('Ancient aliens.', 'WEED'),
('Huge popcorn nugs of hairy alien weed.', 'WEED'),
('Too much edibles.', 'WEED'),
('An eight-foot man smoking a six-foot bong.', 'WEED'),
('Unbelievably soft carpet.', 'WEED'),
('Dropping stuff and knocking everything over.', 'WEED'),
('My own fingers.', 'WEED'),
('The banks, the media, the entire system, man.', 'WEED'),
('A sandwich with Cheetos in it!', 'WEED'),
('A bong rip so massive it restores justice to the kingdom.', 'WEED'),
('Being too high for airplane.', 'WEED'),
('Hot tub.', 'WEED'),
('Eating all the skin off a rotisserie chicken.', 'WEED'),
('Smoking a joint with former President Barack Obama.', 'WEED'),
('Getting high and watching Planet Earth.', 'WEED'),
('A fun, sexy time at the nude beach.', 'WWW'),
('A complete inability to understand anyone else&apos;s perspective.', 'WWW'),
('Three years of semen in a shoebox.', 'WWW'),
('A respectful discussion of race and gender on the Internet.', 'WWW'),
('Taking a shit while running at full speed.', 'WWW'),
('A night of Taco Bell and anal sex.', 'WWW'),
('Googling.', 'WWW'),
('Smash Mouth.', 'WWW'),
('A man from Craigslist.', 'WWW'),
('My browser history.', 'WWW'),
('Getting teabagged by a fifth grader in Call of Duty.', 'WWW'),
('My privileged white penis.', 'WWW'),
('Internet porn analysis paralysis.', 'WWW'),
('YouTube comments.', 'WWW'),
('Pretending to be black.', 'WWW'),
('That thing on the Internet everyone&apos;s talking about.', 'WWW'),
('Goats screaming like people.', 'WWW'),
('Destroying Dick Cheney&apos;s last horcrux.', 'WWW'),
('Game of Thrones spoilers.', 'WWW'),
('Cat massage.', 'WWW'),
('Matching with Mom on Tinder.', 'WWW');