INSERT INTO `questions` (`blanks`, `question`, `deck`)
VALUES 
 (1, 'Here is the church Here is the steeple Open the doors And there is ____.', 'US'), 
 (1, '50% of all marriages end in ____.', 'US'), 
 (1, 'As the mom of five rambunctious boys, I&#39;m no stranger to ____.', 'US'), 
 (1, 'Next from J.K. Rowling: Harry Potter and the Chamber of ____.', 'US'), 
 (1, 'This is the way the world ends This is the way the world ends Not with a bang but with ____.', 'US'), 
 (1, 'After four platinum albums and three Grammys, it&#39;s time to get back to my roots, to what inspired me to make music in the first place: ____.', 'US'), 
 (1, 'When Pharaoh remained unmoved, Moses called down a Plague of ____.', 'US'), 
 (1, 'What&#39;s there a ton of in heaven?', 'US'), 
 (1, 'It&#39;s a pity that kids these days are all getting involved with ____.', 'US'), 
 (1, 'What&#39;s a girl&#39;s best friend?', 'US'), 
 (1, '____. High five, bro.', 'US'), 
 (2, 'Step 1: ____. Step 2: ____. Step 3: Profit.', 'US'), 
 (1, 'The class field trip was completely ruined by ____.', 'US'), 
 (1, 'If you can&#39;t be with the one you love, love ____.', 'US'), 
 (1, 'When I am a billionaire, I shall erect a 50-foot statue to commemorate ____.', 'US'), 
 (1, 'I&#39;m LeBron James, and when I&#39;m not slamming dunks, I love ____.', 'US'), 
 (1, 'Uh, hey guys, I know this was my idea, but I&#39;m having serious doubts about ____.', 'US'), 
 (1, 'Alternative medicine is now embracing the curative powers of ____.', 'US'), 
 (2, 'I never truly understood ____ until I encountered ____.', 'US'), 
 (1, 'I&#39;m sorry, Professor, but I couldn&#39;t complete my homework because of ____.', 'US'), 
 (1, 'I drink to forget ____.', 'US'), 
 (1, 'Next on ESPN2: The World Series of ____.', 'US'), 
 (1, 'Hey Reddit! I&#39;m ____. Ask me anything.', 'US'), 
 (2, 'That&#39;s right, I killed ____. How, you ask? ____.', 'US'), 
 (1, 'How did I lose my virginity?', 'US'), 
 (1, 'I&#39;m going on a cleanse this week. Nothing but kale juice and ____.', 'US'), 
 (1, 'Dear Abby, I&#39;m having some trouble with ____ and would like your advice.', 'US'), 
 (1, '____. That was so metal.', 'US'), 
 (1, 'I got 99 problems but ____ ain&#39;t one.', 'US'), 
 (1, 'Why can&#39;t I sleep at night?', 'US'), 
 (1, 'Dude, do not go in that bathroom. There&#39;s ____ in there.', 'US'), 
 (2, 'Lifetime&reg; presents "____: the Story of ____."', 'US'), 
 (1, 'Hey guys, welcome to Chili&#39;s! Would you like to start the night off right with ____?', 'US'), 
 (1, 'Just once, I&#39;d like to hear you say "Thanks, Mom. Thanks for ____."', 'US'), 
 (1, 'Old Macdonald had ____. E-I-E-I-O.', 'US'), 
 (1, 'What made my first kiss so awkward?', 'US'), 
 (1, 'Just saw this upsetting video! Please retweet!! #stop____', 'US'), 
 (1, 'What never fails to liven up the party?', 'US'), 
 (1, 'Kids, I don&#39;t need drugs to get high. I&#39;m high on ____.', 'US'), 
 (2, 'When I was tripping on acid, ____ turned into ____.', 'US'), 
 (1, 'Life for American Indians was forever changed when the White Man introduced them to ____.', 'US'), 
 (1, 'Men&#39;s Wearhouse. You&#39;re gonna like ____. I guarantee it.', 'US'), 
 (1, '____. Betcha can&#39;t have just one!', 'US'), 
 (1, 'Instead of coal, Santa now gives the bad children ____.', 'US'), 
 (1, 'The Chevy Tahoe. With the power and space to take ____ everywhere you go.', 'US'), 
 (1, 'Click here for ____!!!', 'US'), 
 (1, 'TSA guidelines now prohibit ____ on airplanes.', 'US'), 
 (1, 'What would grandma find disturbing, yet oddly charming?', 'US'), 
 (1, 'What&#39;s that sound?', 'US'), 
 (1, 'What is Batman&#39;s guilty pleasure.', 'US'), 
 (1, 'After eight years in the White House, how is Obama finally letting loose?', 'US'), 
 (1, 'This season at Steppenwolf, Samuel Beckett&#39;s classic existential play: Waiting for ____.', 'US'), 
 (1, 'A recent laboratory study shows that undergraduates have 50% less sex after being exposed to ____.', 'US'), 
 (2, 'Introducing the amazing superhero/sidekick duo! It&#39;s ____ and ____!', 'US'), 
 (1, 'Mabe she&#39;s born with it. Maybe it&#39;s ____.', 'US'), 
 (2, 'They said we were crazy. They said we couldn&#39;t put ____ inside of ____. They were wrong.', 'US'), 
 (1, 'Arby&#39;s: We Have ____.', 'US'), 
 (1, 'What will always get you laid?', 'US'), 
 (1, 'My fellow Americans: Before this decade is out, we will have ____ on the moon!', 'US'), 
 (1, 'What ended my last relationship?', 'US'), 
 (1, 'Why do I hurt all over?', 'US'), 
 (1, 'When I am President, I will create the Department of ____.', 'US'), 
 (1, 'But before I kill you, Mr. Bond, I must show you ____.', 'US'), 
 (1, 'What&#39;s Teach For America using to inspire inner city students to succeed?', 'US'), 
 (1, 'War! What is it good for?', 'US'), 
 (2, 'In M. Night Shyamalan&#39;s new movie, Bruce Willis discovers that ____ had really been ____ all along.', 'US'), 
 (1, 'Military historians remember Alexander the Great for his brilliant use of ____ against the Persians.', 'US'), 
 (1, 'A romantic, candlelit dinner would be incomplete without ____.', 'US'), 
 (1, 'Coming to Broadway this season, ____: The Musical.', 'US'), 
 (1, 'Brought to you by Bud Light&reg;, the official Beer of ____.', 'US'), 
 (1, 'Check me out, yo! I call this dance move "____."', 'US'), 
 (2, 'And the Academy Award for ____ goes to ____.', 'US'), 
 (1, 'Introducing X-treme Baseball! It&#39;s like baseball, but with ____!', 'US'), 
 (1, 'Fun tip! When your man asks you to go down on him, try surprising him with ____ instead.', 'US'), 
 (1, 'I&#39;m no doctor but I&#39;m pretty sure what you&#39;re suffering from is called "____."', 'US'), 
 (1, 'Bravo&#39;s new reality show features eight washed-up celebrities living with ____.', 'US'), 
 (1, 'White people like ____.', 'US'), 
 (1, '____: kid-tested, mother-approved.', 'US'), 
 (1, 'IF you like ____, YOU MIGHT BE A REDNECK.', 'US'), 
 (1, 'What gives me uncontrollable gas?', 'US'), 
 (2, '____ is a slippery slope that leads to ____.', 'US'), 
 (1, 'Today on Maury : "Help! My son is ____!"', 'US'), 
 (1, 'What is George W. Bush thinking about right now?', 'US'), 
 (2, 'For my next trick, I will pull ____ out of ____.', 'US'), 
 (1, 'What&#39;s that smell?', 'US'), 
 (1, '____. It&#39;s a trap!', 'US'), 
 (1, 'Well if you&#39;ll excuse me, gentlemen, I have a date with ____.', 'US'), 
 (1, '&#x2605;&#x2606;&#x2606;&#x2606;&#x2606; Do NOT go here! Found ____ in my Kung Pao chicken!', 'US'), 
 (1, 'Why am I sticky?', 'US'), 
 (1, 'What makes life worth living?', 'US'), 
 (1, 'In the Disney Channel Original Movie, Hannah Montana struggles with ____ for the first time.', 'US'), 
 (1, 'While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on ____.', 'US'), 
 (1, 'What&#39;s my secret power?', 'US'), 
 (1, 'What are my parents hiding from me?', 'US'), 
 (1, 'Daddy, why is mommy crying?', 'US'), 
 (1, 'During sex, I like to think about ____.', 'US'), 
 (1, 'Mr. and Mrs. Diaz, we called you in because we&#39;re concerned about Cynthia. Are you aware that your daughter is ____?', 'US'), 
 (1, 'I get by with a little help from ____.', 'US'), 
 (1, 'I&#39;m no doctor, but I&#39;m pretty sure what you&#39;re suffering from is called "____."', 'CA'), 
 (1, 'As the mom of five rambunctious boys, I&#39;m not stranger to ____.', 'CA'), 
 (2, 'CBC presents "____: the Story of ____."', 'CA'), 
 (1, 'Just once I&#39;d like to hear you say "Thanks, Mom. Thanks for ____."', 'CA'), 
 (1, 'Bravo&#39;s new reality show feature eight washed-up celebrities living with ____.', 'CA'), 
 (1, 'Air Canada guidelines now prohibit ____ on airplanes.', 'CA'), 
 (1, 'When I am Prime Minister of Canada, I will create the Ministry of ____.', 'CA'), 
 (1, 'Coming to Broadway this season, ____; The Musical.', 'CA'), 
 (1, 'This season at the Princess of Wales Theatre, Samuel Beckett&#39;s classic existential play: Waiting for ____.', 'CA'), 
 (1, 'Here is church Here is the steeple Open the doors And there is ____.', 'CA'), 
 (1, 'Penalty! ____: that&#39;s 5 minutes in the box!', 'CA'), 
 (1, 'Click Here for ____!!!', 'CA'), 
 (1, 'Hey guys, welcome to Boston Pizza! Would you like to start the night off right with ____?', 'CA'), 
 (1, 'I know when that hotline bling, that can only mean one thing: ____.', 'CA'), 
 (1, 'Dude, do not go in that washroom. There&#39;s ____ in there.', 'CA'), 
 (1, 'Just saw this upsetting video! Please retweet!! #stop ____', 'CA'), 
 (1, 'Brought to you by Molson Canadian, the Official Beer of ____.', 'CA'), 
 (1, 'Maybe she&#39;s born with it. Maybe it&#39;s ____.', 'CA'), 
 (1, 'Next on TSN: The World Series of ____.', 'CA'), 
 (1, 'A romantic, candlelit dinner would be incomplete without  ____.', 'CA'), 
 (1, 'O Canada, we stand on guard for ____.', 'CA'), 
 (1, 'What is Batman&#39;s guilty pleasure?', 'CA'), 
 (1, 'Old MacDonald has ____. E-I-E-I-O.', 'CA'), 
 (1, 'A recent laboratory study shows that undergraduates have 50% less sex after being exposed to: ____.', 'CA'), 
 (1, 'Dear Abby, I&#39;m having some trouble ____ and would like your advice.', 'CA'), 
 (1, 'In the new Disney Channel Original Movie, Hannah Montana struggles with ____ for the first time.', 'CA'), 
 (1, 'Skidamarink a dink a dink, skidamarink a doo, I love ____.', 'CA'), 
 (1, 'But before I kill you, Mr. Bond, I must show you.', 'CA'), 
 (1, 'The new Chevy Tahoe. With the power and space to take ____ everywhere you go.', 'CA'), 
 (1, 'When I am a billionaire, I shall erect a 20-metre statue to commemorate ____.', 'CA'), 
 (1, 'Airport security guidelines now prohibit ____ on airplanes.', 'UK'), 
 (1, '____? Jim&#39;ll fix it!', 'UK'), 
 (1, 'Daddy, why is mummy crying?', 'UK'), 
 (1, 'Today on The Jeremy Kyle Show: "Help! My son is ____!"', 'UK'), 
 (1, 'What did I bring back from Amsterdam?', 'UK'), 
 (1, 'Mate, do not go in that bathroom. There&#39;s ____ in there.', 'UK'), 
 (1, '____. Once you pop, the fun don&#39;t stop!', 'UK'), 
 (1, 'When I am Prime Minister of the United Kingdom, I will create the Ministry of ____.', 'UK'), 
 (1, 'Instead of coal, Father Christmas now gives the bad children ____.', 'UK'), 
 (1, 'Just once I&#39;d like to hear you say "Thanks, Mum. Thanks for ____."', 'UK'), 
 (1, 'UKIP: Putting ____ First!', 'UK'), 
 (2, 'And the BAFTA for ____ goes to____.', 'UK'), 
 (1, 'TFL apologizes for the delay in train service due to ____.', 'UK'), 
 (1, 'Nobody expects the Spanish Inquisition. Our chief weapons are fear, surprise, and ____.', 'UK'), 
 (1, 'The school trip was completely ruined by ____.', 'UK'), 
 (1, 'How am I maintaining my relationship status?', 'UK'), 
 (1, 'As the mum of five rambunctious boys, I&#39;m not stranger to ____.', 'UK'), 
 (1, 'Next on Sky Sports: The World Champion of ____..', 'UK'), 
 (1, 'What&#39;s the next Happy Meal&reg; toy?', 'UK'), 
 (1, 'The theme for next year&#39;s Eurovision Song Contest is "We are ____."', 'UK'), 
 (1, 'Next up on Channel 4: Ramsay&#39;s ____ Nightmares.', 'UK'), 
 (1, 'In Belmarsh Prison, word is you can trade 200 cigarettes for ____.', 'UK'), 
 (1, 'Now at the Natural History Museum: an interactive exhibit on ____.', 'UK'), 
 (1, 'Hey guys, welcome to TGIF! Would you like to start the night off right with ____?', 'UK'), 
 (1, 'Coming to the West End this year, ____: The Musical.', 'UK'), 
 (2, 'In a world ravaged by ____, our only solace is ____.', 'UK'), 
 (1, 'This season at the Old Vic, Samuel Beckett&#39;s classic existential play: Waiting for ____.', 'UK'), 
 (1, 'Channel 5&#39;s new reality show feature eight washed-up celebrities living with ____.', 'UK'), 
 (1, 'I&#39;m sorry, Sir, but I couldn&#39;t complete my homework because of ____.', 'UK'), 
 (1, '____. That&#39;s what mums go to Iceland.', 'UK'), 
 (2, 'Channel 4 presents "____: the Story of ____."', 'UK'), 
 (1, 'Dear Agony Aunt, I&#39;m having some trouble with ____ and would like your advice.', 'UK'), 
 (1, 'Oi! Show us ____!', 'AU'), 
 (1, 'What did I bring back from Bali?', 'AU'), 
 (1, 'MTV&#39;s new reality show features eight washed-up celebrities living with ____.', 'AU'), 
 (1, '&#x2605;&#x2606;&#x2606;&#x2606;&#x2606; Do NOT go here! Found ____ in my Mongolian chicken!', 'AU'), 
 (1, 'What broke up the original Wiggles?', 'AU'), 
 (1, 'Today on Jerry Springer: "Help! My son is ____!"', 'AU'), 
 (1, 'This season at the Sydney Opera House, Samuel Beckett&#39;s classic existential play: Waiting for ____.', 'AU'), 
 (1, 'Crikey! I&#39;ve never seen ____ like this before! Let&#39;s get a bit closer.', 'AU'), 
 (1, 'What&#39;s there a tonne of in heaven?', 'AU'), 
 (1, 'What makes me a true blue Aussie?', 'AU'), 
 (1, 'The school excursion was completely ruined by ____.', 'AU'), 
 (1, 'Channel 9 is pleased to present its new variety show, "Hey Hey It&#39;s ____."', 'AU'), 
 (1, 'Qantas now prohibits ____ on airplanes.', 'AU'), 
 (2, 'ABC presents "____: the Story of ____."', 'AU'), 
 (1, 'Next on Nine&#39;s Wide World of Sports: The World Series of ____.', 'AU'), 
 (1, 'Are you thinking what I&#39;m thinking, B1? I think I am, B2: it&#39;s ____ time!', 'AU'), 
 (1, '____? Yeah, nah.', 'AU'), 
 (1, 'Life for Aboriginal people was forever changed when the white man introduced them to ____.', 'AU'), 
 (1, 'Hey guys, welcome to Sizzler! Would you like to start the night off right with ____?', 'AU'), 
 (1, 'Brought to you by XXXX Gold, the Official Beer of ____.', 'AU'), 
 (1, 'Mate, do not go in that toilet. There&#39;s ____ in there.', 'AU'), 
 (1, 'In Australia, ____ is twice as big and twice as deadly.', 'AU'), 
 (1, 'When I am Prime Minister, I will create the Department of ____.', 'AU'), 
 (1, 'What brought the orgy to a grinding halt?', 'INTL'), 
 (1, 'Lovin&#39; you is easy &#39;cause you&#39;re ____.', 'INTL'), 
 (1, 'Your persistence is admirable, my dear Prince. But you cannot win my heart with ____ alone.', 'INTL'), 
 (1, 'The blind date was going horrible until we discovered our shared interest in ____.', 'INTL'), 
 (1, 'Science will never explain ____.', 'INTL'), 
 (1, 'The Five Stages of Grief: denial, anger, bargaining, ____, acceptance.', 'INTL'), 
 (1, 'What has been making life difficult at the nudist colony?', 'INTL'), 
 (1, 'Charades was ruined for me forever when my mom had to act out ____.', 'INTL'), 
 (1, 'Money can&#39;t buy me love, but it can buy me ____.', 'INTL'), 
 (1, 'During his midlife crisis, my dad got really into ____.', 'INTL'), 
 (2, 'When you get right down to it, ____ is just ____.', 'INTL'), 
 (1, 'This is your captain speaking. Fasten your seatbelts and prepare for ____.', 'INTL'), 
 (1, 'Tonight&#39;s top story: What you don&#39;t know about ____ could kills you.', 'INTL'), 
 (1, 'Future historians will agree that ____ marked the beginning of America&#39;s decline.', 'INTL'), 
 (1, 'Coming this season, Samuel Beckett&#39;s classic existential play: Waiting for ____.', 'INTL'), 
 (1, 'When I pooped, what came out of my butt?', 'INTL'), 
 (1, 'A successful job interview begins with a firm handshake and ends with ____.', 'INTL'), 
 (1, 'Finally! A service that delivers ____ right to your door.', 'INTL'), 
 (1, 'And what did you bring for show and tell?', 'INTL'), 
 (1, 'When I am a billionaire, I shall erect a 20-meter statue to commemorate ____.', 'INTL'), 
 (1, 'When all else fails, I can always masturbate to ____.', 'INTL'), 
 (2, 'I spent my whole life working toward ____, only to have it ruined by ____.', 'INTL'), 
 (2, '____ would be woefully incomplete without ____.', 'INTL'), 
 (1, 'Next on Eurosport: The World Championship of ____.', 'INTL'), 
 (1, 'In his new self-produced album, Kanye West raps over the sounds of ____.', 'INTL'), 
 (1, 'In Rome, there are whisperings that the Vatican has a secret room devoted to ____.', 'INTL'), 
 (2, 'Having problems with ____? Try ____!', 'INTL'), 
 (1, 'The secret to a lasting marriage is communication, communication, and ____.', 'INTL'), 
 (2, 'My mom freaked out when she looked at my browser history and found ____.com/____.', 'INTL'), 
 (1, 'In the seventh circle of Hell, sinners must endure ____ for all eternity.', 'INTL'), 
 (1, '____. Awesome in theory, kind of a mess in practice.', 'INTL'), 
 (1, 'My plan for world domination begins with ____.', 'INTL'), 
 (1, 'I learned the hard way that you can&#39;t cheer up a grieving friend with ____.', 'INTL'), 
 (1, 'A remarkable new study shows that chimps have evolved their own primitive version of ____.', 'INTL'), 
 (2, 'After months of practice with ____, I think I&#39;m finally ready for ____.', 'INTL'), 
 (1, 'When I am Prime Minister, I will create the Ministry of ____.', 'INTL'), 
 (1, 'Turns out that ____-Man was neither the hero we needed nor wanted.', 'INTL'), 
 (2, 'With enough time and pressure, ____ will turn into ____.', 'INTL'), 
 (1, 'What left this stain on my couch?', 'INTL'), 
 (2, 'Dear Sir or Madam, We regret to inform you that the Office of ____ has denied your request for ____.', 'INTL'), 
 (1, 'I&#39;m not like the rest of you. I&#39;m too rich and busy for ____.', 'INTL'), 
 (1, 'The healing process began when I joined a support group for victims of ____.', 'INTL'), 
 (1, 'Doctor, you&#39;ve gone too far! The human body wasn&#39;t meant to withstand that amount of ____!', 'INTL'), 
 (1, 'Only two things in life are certain: death and ____.', 'INTL'), 
 (1, 'This month&#39;s Cosmo: "Spice up your sex life by bringing ____ into the bedroom."', 'RED'), 
 (1, 'Next time on Dr. Phil: How to talk to your child about ____.', 'RED'), 
 (1, 'Tonight on 20/20: What you don&#39;t know about ____ could kill you.', 'RED'), 
 (1, 'My new favorite porn star is Joey "____" McGee.', 'RED'), 
 (2, 'Michael Bay&#39;s new three-hour action epic pits ____ against ____.', 'RED'), 
 (2, 'Before ____, all we had was ____.', 'RED'), 
 (1, 'Aww, sick! I just saw this skater do a 720 kickflip into ____!', 'RED'), 
 (1, 'What&#39;s harshing my mellow, man?', 'RED'), 
 (1, 'I love being a mom. But it&#39;s tough when my kids come home filthy from ____. That&#39;s why there&#39;s Tide&reg;.', 'RED'), 
 (1, 'As part of his daily regimen, Anderson Cooper sets aside 15 minutes for ____.', 'RED'), 
 (1, 'To prepare for his upcoming role, Daniel Day-Lewis immersed himself in the world of ____.', 'RED'), 
 (1, 'Welcome to Se&ntilde;or Frog&#39;s! Would you like to try our signature cocktail, "____ on the Beach"?', 'RED'), 
 (1, 'Hey baby, come back to my place and I&#39;ll show you ____.', 'RED'), 
 (2, 'You haven&#39;t truly lived until you&#39;ve experienced ____ and ____ at the same time.', 'RED'), 
 (1, 'Your persistence is admirable, my dear Prince, But you cannot win my heart with ____ alone.', 'RED'), 
 (2, 'In a pinch, ____ can be a suitable substitute for ____.', 'RED'), 
 (1, 'During high school, I never really fit in until I found ____ club.', 'RED'), 
 (1, 'Little Miss Muffet<br>Sat on a tuffet,<br>Eating her curds<br>and ____.', 'RED'), 
 (1, 'In its new tourism campaign, Detroit proudly proclaims that it has finally eliminated ____.', 'RED'), 
 (1, 'My gym teacher got fired for adding ____ to the obstacle course.', 'RED'), 
 (1, 'The blind date was going horribly until we discovered our shared interest in ____.', 'RED'), 
 (1, 'My country, &#39;tis of thee, sweet land of ____.', 'RED'), 
 (1, 'Call the law offices of Goldstein &amp; Goldstein, because no one should have to tolerate ____ in the workplace.', 'RED'), 
 (1, 'Members of New York&#39;s social elite are paying thousands of dollars just to experience ____.', 'RED'), 
 (1, 'In his newest and most difficult stunt, David Blaine must escape from ____.', 'RED'), 
 (2, 'Dear Sir or Madam, <br>We regret to inform you that the Office of ____ has denied your request for ____.', 'RED'), 
 (2, '____: Hours of fun. Easy to use. Perfect for ____!', 'RED'), 
 (2, 'Listen, son. If you want to get involved with ____, I won&#39;t stop you. Just steer clear of ____.', 'RED'), 
 (1, 'Next week on the Discovery Channel, one man must survive in the depths of the Amazon with only ____ and his wits.', 'RED'), 
 (2, 'If God didn&#39;t want us to enjoy ____, he wouldn&#39;t have given us ____.', 'RED'), 
 (2, 'My life is ruined by a vicious cycle of ____ and ____.', 'RED'), 
 (1, 'And I would have gotten away with it, too, if it hadn&#39;t been for ____!', 'RED'), 
 (1, 'Legend has it Prince wouldn&#39;t perform without ____ in his dressing room.', 'RED'), 
 (1, 'Dear Leader Kim Jong-un, our village praises your infinite wisdom with a humble offering of ____.', 'BLUE'), 
 (2, 'We never did find ____, but along the way we sure learned a lot about ____.', 'BLUE'), 
 (1, 'Do not fuck with me! I am literally ____ right now.', 'BLUE'), 
 (1, 'And would you like those buffalo wings mild, hot, or ____?', 'BLUE'), 
 (1, 'What&#39;s fun until it gets weird?', 'BLUE'), 
 (1, 'And today&#39;s soup is Cream of ____.', 'BLUE'), 
 (1, 'Come to Dubai, where you can relax in our world-famous spas, experience the nightlife, or simply enjoy ____ by the poolside.', 'BLUE'), 
 (1, 'She&#39;s up all night for good fun. I&#39;m up all night for ____.', 'BLUE'), 
 (1, 'Hi MTV! My name is Kendra, I live in Malibu, I&#39;m into ____, and I love to have a good time.', 'BLUE'), 
 (2, 'I am become ____, destroyer of ____!', 'BLUE'), 
 (2, '____ may pass, but ____ will last forever.', 'BLUE'), 
 (2, 'In the beginning, there was ____. And the Lord said, "Let there be ____."', 'BLUE'), 
 (2, 'This year&#39;s hottest album is "____" by ____.', 'BLUE'), 
 (1, '"This is madness!"<br><br>" No. THIS IS ____!"', 'BLUE'), 
 (1, 'It lurks in the night. It hungers for flesh. This summer, no one is safe from ____.', 'BLUE'), 
 (2, '____ will never be the same after ____.', 'BLUE'), 
 (1, 'I don&#39;t mean to brag, but they call me the Michael Jordan of ____.', 'BLUE'), 
 (1, 'Don&#39;t forget! Beginning this week, Casual Friday will officially become "____ Friday."', 'BLUE'), 
 (1, 'Having the worst day EVER. #____', 'BLUE'), 
 (1, 'Why am I broke?', 'BLUE'), 
 (1, 'Wes Anderson&#39;s new film tells the story of a precocious child coming to terms with ____.', 'BLUE'), 
 (2, 'Adventure. Romance. ____. From Paramount Pictures, "____."', 'BLUE'), 
 (2, 'Patient presents with ____. Likely a result of ____.', 'BLUE'), 
 (1, 'Yo&#39; mama so fat she ____!', 'BLUE'), 
 (1, 'Now in bookstores: "The Audacity of ____," by Barack Obama.', 'BLUE'), 
 (1, 'In his new action comedy, Jackie Chan must fend off ninjas while also dealing with ____.', 'BLUE'), 
 (1, 'Armani suit: $1,000. Dinner for two at that swanky restaurant: $300. The look on her face when you surprise her with ____: priceless.', 'BLUE'), 
 (1, 'Behind every powerful man is ____.', 'BLUE'), 
 (1, 'Life&#39;s pretty tough in the fast lane. That&#39;s why I never leave the house without ____.', 'BLUE'), 
 (1, 'You are not alone. Millions of Americans struggle with ____ every day.', 'BLUE'), 
 (1, 'My grandfather worked his way up from nothing. When he came to this country, all he had was the shoes on his feet and ____.', 'BLUE'), 
 (2, 'If you can&#39;t handle ____, you&#39;d better stay away from ____.', 'BLUE'), 
 (1, 'Man, this is bullshit. Fuck ____.', 'BLUE'), 
 (2, 'In return for my soul, the Devil promised me ____, but all I got was ____.', 'BLUE'), 
 (1, 'The Japanese have developed a smaller, more efficient version of ____.', 'BLUE'), 
 (1, 'Do you lack energy? Does it sometimes feel like the whole world is ____? Ask your doctor about Zoloft&reg;.', 'BLUE'), 
 (1, 'I work my ass off all day for this family, and this is what I come home to? ____!?', 'BLUE'), 
 (1, 'This is America. If you don&#39;t work hard, you don&#39;t succeed. I don&#39;t care if you&#39;re black, white, purple, or ____.', 'BLUE'), 
 (1, 'Dammit, Gary. You can&#39;t just solve every problem with ____.', 'BLUE'), 
 (1, 'James is a lonely boy. But when he discovers a secret door in his attic, he meets a magical new friend: ____.', 'BLUE'), 
 (1, 'This is the prime of my life. I&#39;m young, hot, and full of ____.', 'BLUE'), 
 (2, 'Every step towards ____ gets me a little bit closer to ____.', 'BLUE'), 
 (2, 'Well if ____ is good enough for ____, it&#39;s good enough for me.', 'BLUE'), 
 (1, 'WHOOO! God damn I love ____!', 'BLUE'), 
 (1, 'You Won&#39;t Believe These 15 Hilarious ____ Bloopers!', 'BLUE'), 
 (1, 'You&#39;ve seen the bearded lady! You&#39;ve seen the ring of fire! Now, ladies and gentlemen, feast your eyes upon ____!', 'BLUE'), 
 (1, 'When I was a kid, we used to play Cowboys and ____.', 'BLUE'), 
 (1, 'Do the Dew&reg; with our most extreme flavor yet! Get ready for Mountain Dew ____!', 'BLUE'), 
 (2, 'Honey, I have a new role-play I want to try tonight! You can be ____, and I&#39;ll be ____.', 'BLUE'), 
 (2, 'Forget everything you know about ____, because now we&#39;ve supercharged it with ____!', 'BLUE'), 
 (1, 'What&#39;s making things awkward in the sauna?', 'BLUE'), 
 (1, 'Listen, Gary, I like you. But if you want that corner office, you&#39;re going to have to show me ____.', 'BLUE'), 
 (1, 'Help me doctor, I&#39;ve got ____ in my butt.', 'BLUE'), 
 (2, 'Oprah&#39;s book of the month is "____ For ____: A Story of Hope."', 'BLUE'), 
 (2, 'You know, once you get past ____, ____ ain&#39;t so bad.', 'BLUE'), 
 (1, 'In his farewell address, George Washington famously warned Americans about the dangers of ____.', 'BLUE'), 
 (1, 'Well what do you have to say for yourself, Casey? This is the third time you&#39;ve been sent to the principal&#39;s office for ____.', 'BLUE'), 
 (1, 'Here at the Academy for Gifted Children, we allow students to explore ____ at their own pace.', 'BLUE'), 
 (1, 'Get ready for the movie of the summer! One cop plays by the book. The other&#39;s only interested in one thing: ____.', 'BLUE'), 
 (2, 'Heed my voice, mortals! I am the god of ____, and I will not tolerate ____!', 'BLUE'), 
 (1, 'As king, how will I keep the peasants in line?', 'BLUE'), 
 (1, 'I&#39;m sorry, sir, but we don&#39;t allow ____ at the country club.', 'BLUE'), 
 (1, '2 AM in the city that never sleeps. The door swings open and she walks in, legs up to here. Something in her eyes tells me she&#39;s looking for ____.', 'BLUE'), 
 (1, 'I have a strict policy. First date, dinner. Second date, kiss. Third date, ____.', 'BLUE'), 
 (1, 'What killed my boner?', 'BLUE'), 
 (1, 'Hi, this is Jim from accounting. We noticed a $1,200 charge labeled "____." Can you explain?', 'BLUE'), 
 (1, 'I&#39;m pretty sure I&#39;m high right now, because I&#39;m absolutely mesmerized by ____.', 'BLUE'), 
 (1, 'Don&#39;t worry, kid. It gets better. I&#39;ve been living with ____ for 20 years.', 'BLUE'), 
 (1, 'How am I compensating for my tiny penis?', 'BLUE'), 
 (1, 'Ooo, daddy like ____.', 'GREEN'), 
 (1, 'As reparations for slavery, all African Americans will receive ____.', 'GREEN'), 
 (1, 'What&#39;s about to take this dance floor to the next level?', 'GREEN'), 
 (1, 'What are all those whales singing about?', 'GREEN'), 
 (1, 'I&#39;ve got rhythm, I&#39;ve got music, I&#39;ve got ____. Who could ask for anything more?', 'GREEN'), 
 (1, 'Then the princess kissed the frog, and all of a sudden the frog was ____!', 'GREEN'), 
 (1, 'What turned me into a Republican?', 'GREEN'), 
 (1, 'If at first you don&#39;t succeed, try ____.', 'GREEN'), 
 (1, 'Poor Brandon, still living in his parents&#39; basement. I hear he never got over ____.', 'GREEN'), 
 (1, 'Coming to Red Lobster&reg; this month, ____.', 'GREEN'), 
 (1, 'Most Americans would not vote for a candidate who is openly ____.', 'GREEN'), 
 (1, 'This Friday at the Liquid Lounge, it&#39;s ____ Night! Ladies drink free.', 'GREEN'), 
 (1, 'Well, shit. My eyes ain&#39;t so good, but I&#39;ll eat my own boot if that ain&#39;t ____!', 'GREEN'), 
 (1, 'CNN breaking news! Scientists discover ____.', 'GREEN'), 
 (1, 'She&#39;s a lady in the streets, ____ in the sheets.', 'GREEN'), 
 (1, 'There is no God. It&#39;s just ____ and then you die.', 'GREEN'), 
 (1, 'Best you go back where you came from, now. We don&#39;t take too kindly to ____ in these parts.', 'GREEN'), 
 (1, 'I&#39;ve had a horrible vision, father. I saw mountains crumbling, stars falling from the sky. I saw ____.', 'GREEN'), 
 (1, 'Oh no! Siri, how do I fix ____?', 'GREEN'), 
 (1, 'Girls just wanna have ____.', 'GREEN'), 
 (1, 'What&#39;s the gayest?', 'GREEN'), 
 (1, 'Son, take it from someone who&#39;s been around the block a few times. Nothin&#39; puts her in the mood like ____.', 'GREEN'), 
 (1, 'Mom&#39;s to-do list:<br><br>Buy groceries<br>Clean up ____<br>Soccer practice', 'GREEN'), 
 (1, 'What will end racism once and for all?', 'GREEN'), 
 (1, 'No, no, no, no, no, NO! I will NOT let ____ ruin this wedding.', 'GREEN'), 
 (1, 'Summer lovin&#39;, had me a blast. ____, happened so fast.', 'GREEN'), 
 (1, 'I&#39;m sorry, sir, but your insurance plan doesn&#39;t cover injuries caused by ____.', 'GREEN'), 
 (1, 'What sucks balls?', 'GREEN'), 
 (1, 'Errbody in the club ____.', 'GREEN'), 
 (1, 'I&#39;ll take the BBQ bacon burger with a fried egg and fuck it how about ____.', 'GREEN'), 
 (1, 'You won&#39;t believe what&#39;s in my pussy. It&#39;s ____.', 'GREEN'), 
 (1, 'The top Google auto-complete results for "Barack Obama": <br>Barack Obama height.<br>Barack Obama net worth.<br>Barack Obama ____.', 'GREEN'), 
 (1, 'I may not be much to look at, but I fuck like ____.', 'GREEN'), 
 (1, 'LSD + ____ = really bad time.', 'GREEN'), 
 (1, 'Feeling so grateful! #amazing #mylife #____', 'GREEN'), 
 (1, 'Art isn&#39;t just a painting in a stuffy museum. Art is alive. Art is ____.', 'GREEN'), 
 (1, 'Why am I laughing and crying and taking off my clothes?', 'GREEN'), 
 (1, 'Google Calendar alert: ____ in 10 minutes.', 'GREEN'), 
 (1, 'One more thing. Watch out for Big Mike. They say he killed a man with ____.', 'GREEN'), 
 (1, 'Dance like there&#39;s nobody watching, love like you&#39;ll never be hurt, and live like you&#39;re ____.', 'GREEN'), 
 (2, '____: Brought to you by ____.', 'GREEN'), 
 (1, 'In the 1950s, psychologists prescribed ____ as a cure for homosexuality.', 'GREEN'), 
 (1, 'Well if ____ is a crime, then lock me up!', 'GREEN'), 
 (1, 'Run, run, as fast as you can! You can&#39;t catch me, I&#39;m ____!', 'GREEN'), 
 (1, 'What&#39;s the most problematic?', 'GREEN'), 
 (1, 'With a one-time gift of just $10, you can save this child from ____.', 'GREEN'), 
 (2, '____ be all like ____.', 'GREEN'), 
 (1, 'You know who else liked ____? Hitler.', 'GREEN'), 
 (1, 'What totally destroyed my asshole?', 'GREEN'), 
 (1, 'I don&#39;t believe in God. I believe in ____.', 'GREEN'), 
 (1, 'She&#39;s just one of the guys, you know? She likes beer, and football, and ____.', 'GREEN'), 
 (1, 'Congratulations! You have been selected for our summer internship program. While we are unable to offer a salary, we can offer you ____.', 'GREEN'), 
 (1, 'I tell you, it was a non-stop fuckfest. When it was over, my asshole looked like ____.', 'GREEN'), 
 (1, 'We do not shake with our left hands in this country. That is the hand we use for ____.', 'GREEN'), 
 (1, 'As Teddy Roosevelt said, the four manly virtues are honor, temperance, industry, and ____.', 'GREEN'), 
 (1, 'How did Stella get her groove back?', '90s'), 
 (1, 'Siskel and Ebert have panned ____ as "poorly conceived" and "sloppily executed."', '90s'), 
 (1, 'Up next on Nickelodeon: "Clarissa Explains ____."', '90s'), 
 (1, 'It&#39;s Morphin&#39; Time! Mastodon! Pterodactyl! Triceratops! Sabertooth Tiger! ____!', '90s'), 
 (1, 'Believe it or not, Jim Carrey can do a dead-on impression of ____.', '90s'), 
 (1, 'I&#39;m a bitch, I&#39;m a lover, I&#39;m a child, I&#39;m ____.', '90s'), 
 (1, 'Tonight on SNICK: "Are You Afraid of ____?"', '90s'), 
 (1, 'Jesus is ____.', '2012'), 
 (1, 'When you go to the polls on Tuesday, remember: a vote for me is a vote for ____.', 'V4HIL'), 
 (1, 'Senator, I trust you enjoyed ____ last night. Now, can I count on your vote?', 'V4HIL'), 
 (1, 'Trump&#39;s great! Trump&#39;s got ____. I love that.', '45'), 
 (1, 'I can&#39;t believe Netflix is using ____ to promote House of Cards.', 'HCARD'), 
 (1, 'A wise man said, "Everything is about sex. Except sex. Sex is about ____."', 'HCARD'), 
 (1, 'I&#39;m not going to lie. I despise ____. There, I said it.', 'HCARD'), 
 (2, 'Corruption. Betrayal. ____. Coming soon to Netflix, "House of ____."', 'HCARD'), 
 (1, 'We&#39;re not like other news organizations. Here at Slugline, we welcome ____ in the office.', 'HCARD'), 
 (2, 'Because you enjoyed ____, we thought you&#39;d like ____.', 'HCARD'), 
 (1, 'Cancel all my meetings. We&#39;ve got a situation with ____ that requires my immediate attention.', 'HCARD'), 
 (1, 'Our relationship is strictly professional. Let&#39;s not complicate things with ____.', 'HCARD'), 
 (1, 'My memory of last night is pretty hazy. I remember ____ and that&#39;s pretty much it.', 'COLEG'), 
 (1, 'Pledges! Time to prove you&#39;re Delta Phi material. Chug this beer, take off your shirts, and get ready for ____.', 'COLEG'), 
 (1, 'All classes today are canceled due to ____.', 'COLEG'), 
 (1, 'Did you know? Our college was recently named the #1 school for ____!', 'COLEG'), 
 (1, 'The Department of Psychology is looking for paid research volunteers. Are you 18-25 and suffering from ____?', 'COLEG'), 
 (1, 'In this paper, I will explore ____ from a feminist perspective.', 'COLEG'), 
 (2, 'Critics are raving about HBO&#39;s new Game of Thrones spin-off, "____ of ____."', 'FNTSY'), 
 (1, 'Your father was a powerful wizard, Harry. Before he died, he left you something very precious: ____.', 'FNTSY'), 
 (1, 'Having tired of poetry and music, the immortal elves now fill their days with ____.', 'FNTSY'), 
 (1, 'And in the end, the dragon was not evil; he just wanted ____.', 'FNTSY'), 
 (1, 'Who blasphemes and bubbles at the center of all infinity, whose name no lips dare speak aloud, and who gnaws hungrily in inconceivable, unlighted chambers beyond time?', 'FNTSY'), 
 (1, 'Legend tells of a princess who has been asleep for a thousand years and can only be awoken by ____.', 'FNTSY'), 
 (1, 'Coming this spring from BioWare, Mass Effect: ____.', 'MSFX'), 
 (1, 'I&#39;m Commander Shepard, and this is my favorite place for ____ on the Citadel.', 'MSFX'), 
 (1, 'It turns out The Reapers didn&#39;t want to destroy the galaxy. They just wanted ____.', 'MSFX'), 
 (1, 'We were the best hand-to-hand combatants on the ship. I had reach, but she had ____.', 'MSFX'), 
 (1, 'Behold the Four Horsemen of the Apocalypse! War, Famine, Death, and ____.', '2014'), 
 (1, 'Honey, Mommy and Daddy love you very much.But apparently Mommy loves ____ more than she loves Daddy.', '2014'), 
 (2, 'A curse upon thee! Many years from now, just when you think you&#39;re safe, ____ shall turn into ____.', '2014'), 
 (2, 'Today on Buzzfeed: 10 Pictures of ____ That Look Like ____!', '2014'), 
 (1, 'Why am I so tired?', '2014'), 
 (1, 'Curiosity was put into safe mode after its hazcams detected ____.', 'NASA'), 
 (1, 'NASA will spend 15 billion dollars on an unprecedented mission: ____ in space.', 'NASA'), 
 (1, 'It&#39;s not delivery. It&#39;s ____.', 'FOOD'), 
 (1, 'Don&#39;t miss Rachel Ray&#39;s hit new show, Cooking with ____.', 'FOOD'), 
 (1, 'I&#39;m Bobby Flay, and if you can&#39;t stand ____, get out of the kitchen!', 'FOOD'), 
 (1, 'Now on Netflix: Jiro Dreams of ____.', 'FOOD'), 
 (1, 'Aw babe, your burps smell like ____!', 'FOOD'), 
 (1, 'Excuse me, waiter. Could you take this back? This soup tastes like ____.', 'FOOD'), 
 (1, 'You have been waylaid by ____ and must defend yourself.', 'PE13A'), 
 (1, 'I have an idea even better than Kickstarter, and it&#39;s called ____starter.', 'PE13A'), 
 (1, 'Donna, pick up my dry cleaning and get my wife something for christmas. I think she likes ____.', 'CAH'), 
 (1, 'It&#39;s beginning to look a lot like ____.', 'CAH'), 
 (1, 'In the final round of this year&#39;s Omegathon, Omeganauts must face off in a game of ____.', 'PE13B'), 
 (1, 'Action stations! Action stations! Set condition one throughout the fleet and brace for ____!', 'PE13B'), 
 (1, 'Press &darr;&darr;&larr;&rarr;B to unleash ____.', 'PE13C'), 
 (1, 'I don&#39;t know exactly how I got the PAX plague, but I suspect it had something to do with ____.', 'PE13C'), 
 (2, '____ is way better in ____ mode.', 'GEEK'), 
 (1, '____: Achievement unlocked.', 'GEEK'), 
 (1, '(Heavy breathing) Luke, I am ____.', 'GEEK'), 
 (1, 'What&#39;s the latest bullshit that&#39;s troubling this quaint fantasy town?', 'GEEK'), 
 (1, 'What made Spock cry?', 'GEEK'),
 (1, 'What the hell?! They added a 6/6 with flying, trample, and ____.', 'PXE14'), 
 (2, '____ is way better in ____mode.', 'PXE14'), 
 (1, 'Unfortunately, Neo, no one can be told what ____ is. You have to see it for yourself.', 'PXE14'), 
 (1, 'You think you have defeated me? Well, let&#39;s see how you handle ____!', 'PXE14'), 
 (1, 'What&#39;s so important right now that you can&#39;t call your mother?', 'JEW'), 
 (1, 'According to Freud, all children progress through three stages of development: the oral stage, the anal stage, and the ____ stage.', 'JEW'), 
 (1, 'Oh, your daughter should meet my son! He gives to charity, he loves ____ and did I mention he&#39;s a doctor?', 'JEW'), 
 (1, 'Coming to Broadway next season: "____ on the Roof."', 'JEW'), 
 (1, 'Can&#39;t you see? The Jews are behind everything--the banks, the media, even ____!', 'JEW'), 
 (1, 'In the new DLC for Mass Effect, Shepard must save the galaxy from ____.', '13PAX'), 
 (1, 'The most controversial game at PAX this year is an 8-bit indie platformer about ____.', '13PAX'), 
 (1, 'There was a riot at the Gearbox panel when they gave the attendees ____.', '13PAX'), 
 (1, 'No Enforcer wants to manage the panel on ____.', '13PAX'), 
 (1, 'What gets me wet?', 'CAH'), 
 (1, 'My body, my voice! ____, my choice!', 'CAH'), 
 (1, 'My vagina&#39;s angry. My vagina&#39;s furious and it needs to talk. It needs to talk about ____.,', 'CAH'), 
 (1, 'Can a woman really have it all? A career and ____?', 'CAH'), 
 (1, 'Tampax&reg;: Don&#39;t let your period ruin ____.', 'CAH'), 
 (1, 'New from Mattel, it&#39;s ____ Barbie!', 'CAH'), 
 (1, 'Donald Trump&#39;s first act as president was to outlaw ____.', 'PST45'), 
 (1, 'Donald Trump has nominated ____ for his VP.', 'PST45'), 
 (1, 'In 2019, Donald Trump eliminated our national parks to make room for ____.', 'PST45'), 
 (2, 'What are two cards in your hand that you want to get rid of?', 'RJECT'), 
 (1, 'From WBEZ Chicago, it&#39;s This American Life. Today on our program, ____. Stay with us.', 'RJECT'), 
 (1, 'My name is Inigo Montoya. You killed my father. Prepare for ____.', 'RJECT'), 
 (1, '(rorschach test) What do you see?', 'RJECT'), 
 (1, 'Sir, we found you passed out naked on the side of the road. What&#39;s the last thing you remember?', 'RJECT'), 
 (1, 'You can&#39;t wait forever. It&#39;s time to talk to your doctor about ____.', 'RJECT'), 
 (1, 'The elders of the Ibo tribe of Nigeria recommend ____ as a cure for impotence.', 'RJECT'), 
 (1, 'The Westboro Baptist Church is now picketing soldiers&#39; funerals with signs that read &#39;GOD HATES ____!&#39;', 'RJECT'), 
 (1, 'Looking to earn big bucks? Learn how to make ____ work for you!', 'RTAIL'), 
 (1, 'How are the writers of Cards Against Humanity spending your $25?', 'RTAIL'), 
 (1, 'Fear leads to anger. Anger leads to hate. Hate leads to ____.', 'SCIFI'), 
 (1, 'Computer! Display ____ on screen. Enhance.', 'SCIFI'), 
 (1, 'You&#39;re not going to believe this, but I&#39;m you from the future! You&#39;ve got to stop ____.', 'SCIFI'), 
 (1, 'This won&#39;t be like negotiating with the Vogons. Humans only respond to one thing: ____.', 'SCIFI'), 
 (1, 'Madam President, the asteroid is headed directly for Earth and there&#39;s one one thing that can stop it: ____.', 'SCIFI'), 
 (1, 'You have violated the Prime Directive! You exposed an alien culture to ____ before they were ready.', 'SCIFI'), 
 (1, 'What is the answer to life, the universe, and everything?', 'SCIFI'), 
 (1, 'Why did the chicken cross the road?', 'RJCT2'), 
 (1, 'Some men aren&#39;t looking for anything logical, like money. They can&#39;t be bought, bullied, reasoned, or negotiated with. Some men just want ____.', 'RJCT2'), 
 (1, 'America is hungry. America needs ____.', 'RJCT2'), 
 (1, 'In bourgeois society, capital is independent and has individuality, while the living person is ____.', 'RJCT2'), 
 (1, 'Housekeeping! You want ____?', 'RJCT2'), 
 (1, 'BowWOW! is the first pet hotel in LA that offers ____ for dogs.', 'RJCT2'), 
 (1, 'Astronomers have discovered that the universe consists of 5% ordinary matter, 25% dark matter, and 70% ____.', 'RJCT2'), 
 (1, 'Hey, whatever happened to Renee Zellweger?', 'RJCT2'), 
 (1, 'What&#39;s wrong with these gorillas?', 'RJCT2'), 
 (1, 'You say tomato, I say ____.', 'RJCT2'), 
 (1, 'A study published in Nature this week found that ____ is good for you in small doses.', 'SCI'), 
 (1, 'What really killed the dinosaurs?', 'SCI'), 
 (2, 'In an attempt to recreate conditions just after the Big Bang, physicists at the LHC are observing collisions between ____ and ____.', 'SCI'), 
 (1, 'In what&#39;s being hailed as a major breakthrough, scientists have synthesized ____ in the lab.', 'SCI'), 
 (1, 'Hey there, Young Scientists! Put on your labcoats and strap on your safety goggles, because today we&#39;re learning about ____!', 'SCI'), 
 (2, 'Today on Mythbusters, we find out how long ____ can withstand ____.', 'SCI'), 
 (1, 'Hold up. I gotta deal with ____, then I&#39;mma smoke this.', 'WEED'), 
 (1, 'Okay here&#39;s the pitch. James Franco and Seth Rogen are trying to score some weed, and then ____ happens.', 'WEED'), 
 (1, 'You know what&#39;s like, really funny when you think about it? ____.', 'WEED'), 
 (1, 'Instead of playing a card this round, everyone must stare at the Card Czar while making a sound you&#39;d make after tasting something delicious.', 'WEED'), 
 (1, 'Everyone is staring at you because you&#39;re ____.', 'WEED'), 
 (1, 'Wait, I came here to buy socks. How did I wind up with ____?', 'RTPRD'), 
 (1, 'Hey, you guys want to try this awesome new game? It&#39;s called ____.', 'TBLTP'), 
 (1, 'For my turn, I will spend four gold and allocate all three workers to ____.', 'TBLTP'), 
 (1, 'Backers who supported Tabletop at the $25,000 level were astonished to receive ____ from Wil Wheaton himself.', 'TBLTP'), 
 (1, 'I&#39;m just gonna stay in tonight. You know, Netflix and ____.', 'WWW'), 
 (1, 'What did I nickname my genitals?', 'WWW'), 
 (1, 'This app is basically Tinder, but for ____.', 'WWW'), 
 (1, 'You guys, you can buy ____ on the dark web.', 'WWW'), 
 (1, 'Don&#39;t worry, Penny! Go Go Gadget ____!', 'WWW'), 
 (1, 'TRIGGER WARNING: ____.', 'WWW'), 
 (2, 'I need you like ____ needs ____.', 'WWW'), 
 (2, 'Such ____. Very ____. Wow.', 'WWW'), 
 (1, 'Nothing says &quot;I love you&quot; like ____.', 'WWW');